### ISSUE TITLE
StackBarChart - Show values 

### ISSUE THREAD

**Issue by vanjavanjavanja** [diogobernardino/WilliamChart#100]
Hi, what is a method to show values (doesn't matter OUTSIDE or INSIDE) of bars in StackBarChart?
I saw they are shown on the first BarChart in the example, but can't find the way it is set.

Thank you!

**Comment by diogobernardino** [comment]
```public ChartView setYLabels(AxisController.LabelPosition position)```

Take a look at the [javadoc](http://diogobernardino.github.io/WilliamChart/javadoc/), you will find it in the ```ChartView``` class.

**Comment by vanjavanjavanja** [comment]
Sorry, but that method switched on Y Axis values, not the values on the bars.
What I need is marked in **blue**:
![screenshot](https://i.gyazo.com/681c91b349883df45ae55cc8da613816.png)

**Comment by diogobernardino** [comment]
The ones in blue are tooltips.
Since the latest release of the library was mostly about tooltips I would recommend you to look at the new Sample application in order to give the first steps in how to customize tooltips. Right now it should be even easier to setup something like the ones you mentioned.

**Comment by hu70258tao** [comment]
hi，how to show each value,user HorizontalBarChartView,i am Chinese,English is so so . 
![default](https://user-images.githubusercontent.com/20218008/50049371-657fd080-011f-11e9-84eb-795bcb7f8772.png)

**Comment by hu70258tao** [comment]
i use those code
![default](https://user-images.githubusercontent.com/20218008/50049383-b099e380-011f-11e9-9e9b-f18b3353c3cb.png)
but is do not work as i think
