### ISSUE TITLE
Tooltips to StackBarChartView

### ISSUE THREAD

**Issue by vanjavanjavanja** [diogobernardino/WilliamChart#102]
Trying to add Tooltips to StackBarChartView like ones in your previous version of example app, marked in **blue** here :
![screenshot](https://i.gyazo.com/681c91b349883df45ae55cc8da613816.png)

I'm receiveing `The specified child already has a parent. You must call removeView() on the child's parent first.` in `tiers_battles.showTooltip(mTip, false);`

Here is the code: 
```java
private void show_tiers_battles() {
        String[] labels_tiers = getResources().getStringArray(R.array.labels_tiers);

        mTip = new Tooltip(getActivity(), R.layout.stackedchart_tooltip, R.id.value);
        mTip.setVerticalAlignment(Tooltip.Alignment.TOP_BOTTOM);
        mTip.setDimensions((int) Tools.fromDpToPx(65), (int) Tools.fromDpToPx(25));
        mTip.setEnterAnimation(PropertyValuesHolder.ofFloat(View.ALPHA, 1), PropertyValuesHolder.ofFloat(View.SCALE_Y, 1f), PropertyValuesHolder.ofFloat(View.SCALE_X, 1f)).setDuration(200);
        mTip.setExitAnimation(PropertyValuesHolder.ofFloat(View.ALPHA, 0), PropertyValuesHolder.ofFloat(View.SCALE_Y, 0f), PropertyValuesHolder.ofFloat(View.SCALE_X, 0f)).setDuration(200);
        mTip.setPivotX(Tools.fromDpToPx(65) / 2);
        mTip.setPivotY(Tools.fromDpToPx(25));
        tiers_battles.setTooltips(mTip);

        tiers_battles.setBarSpacing((float) 44.0);
        tiers_battles.setYAxis(false);
        tiers_battles.setYLabels(AxisController.LabelPosition.NONE);
        tiers_battles.setBarBackgroundColor(Color.parseColor("#4D36a19b"));
        tiers_battles.setLabelsColor(Color.parseColor("#ffffff"));
        tiers_battles.setAxisColor(Color.parseColor("#A4A4A4"));

        BarSet dataset = new BarSet(labels_tiers, chartsArrays.getTiers_Battles())
                .setColor(Color.parseColor("#36a19b"));
        tiers_battles.addData(dataset);

        Runnable chartOneAction = new Runnable() {
            @Override
            public void run() {
                ArrayList<Rect> areas = tiers_battles.getEntriesArea(0);
                for(int i = 0; i < areas.size(); i++) {
                    mTip.prepare(areas.get(i), chartsArrays.getTiers_Battles()[i]);
                    mTip.setEnterAnimation(PropertyValuesHolder.ofFloat(View.ALPHA, 1));
                    mTip.setExitAnimation(PropertyValuesHolder.ofFloat(View.ALPHA, 0));
                    tiers_battles.showTooltip(mTip, false);
                }
                run();
            }
        };

        Animation anim = new Animation(500)
                .setEasing(new CubicEase())
                .setAlpha(1)
                .setEndAction(chartOneAction);

        tiers_battles.show(anim);
    }
```

What am I doing wrong? Where would you suggest to look at first?

Thank you

**Comment by diogobernardino** [comment]
What you're doing is to set up a tooltip which would trigger once you click one entry. Instead, what you seem to need, is to force the display of one tooltip per chart entry. 
I would recommend to check the Sample application, either ```LineCardOne.java``` or ```BarChart.java``` have an example of that. The method ```showTooltip()``` forces a tooltip to be displayed once the chart is shown. You can do the same but in all the entries of the chart.

**Comment by vanjavanjavanja** [comment]
That helped a lot, thank you!

**Comment by NishaMore** [comment]
Hi @diogobernardino ,

Thanks a lot for such a awesome library. I am using it recently. But I got the problem that I want to show two values in tooltip. Currently in library we have one constructor which takes only one view. and in prepare() it takes only one value as parameter. So how can I pass the other textview and its value? Please help!

**Comment by diogobernardino** [comment]
You need to build your own Tooltip layout (which will have as manya textview as you wish. You can find examples of custom tooltip layouts in the sample application.

**Comment by NishaMore** [comment]
Hi @diogobernardino 

Thanks for the reply. Actually I have designed custom tooltip layout. but I don't find custom tooltip sample which have two textviews whose value is coming dynamically (e.g. fetching from api). Can you please help me in this regard?

**Comment by diogobernardino** [comment]
I do not necessarily have an example with 2 TextViews. 

From the top of my head... At some point in your code you inflate the custom XML tooltip layout, which then you will do 2 things with it: first you keep those 2 TextViews objects in your activity/fragment (using findViewById), and second you pass this layout to your ```ChartView``` object.
From that point on, the Chart will take care of showing or dismissing your tooltip and you just need to worry changing the values of those 2 TextViews as you wish. In case we are talking about a tooltip which will be shown/dismissed ```onEntryClick``` then you can simply change your TextViews values once a click occurs.

Hope it helps.

**Comment by NishaMore** [comment]
Thanks a lot @diogobernardino 

My Problem:
1. I have dates on X axis and its value on Y-axis. 
2. Now I want to show corrosponding (x,y) on tooltip.
3. I have created xml for custom tooltip which have 2 textviews for the same.
4. I am refering your sample LinecardOne, so did below steps : 
   ```
     mTip = new Tooltip(mContext, R.layout.linechart_tooltip, R.id.price);
Runnable chartAction = new Runnable() {
            @Override
            public void run() {
                mTip.prepare(mChart.getEntriesArea(0).get(3), mValues[0]);
                mChart.showTooltip(mTip, true);
            }
        };

I think here prepare method automatically take correct value of Y axis, but as there is no other prepare method where it can take X axis value as a argument. I don't understand how do I implement this logic?

> . In case we are talking about a tooltip which will be shown/dismissed onEntryClick then you can simply change your TextViews values once a click occurs.

I did this :

```
 mChart.setOnEntryClickListener(new OnEntryClickListener() {
            @Override
            public void onClick(int setIndex, int entryIndex, Rect rect) {
                Toast.makeText(mContext,"setInd : "+setIndex+"\nentryInd : "+entryIndex+"mlable[0]:"+mLabels[0],Toast.LENGTH_LONG).show();
//mLabels[] array contains all X axis values.
            }
        });
```
But this always show first entry in array. How do I get correct X axis value?
Please help!

**Comment by diogobernardino** [comment]
Why do you need the ```chartAction```?

**Comment by NishaMore** [comment]
I copied snippet from your sample. I think it prepares the tooltip to show value. 

Should i remove it? Please tell me how can i show X axis value in tooltip??

**Comment by diogobernardino** [comment]
Sorry, but I can't tell you if you should remove it or not, the only person who knows that is you? 
I think the best is that you try to understand how the sample charts work and then try to implement yours but going slowly step by step.

**Comment by NishaMore** [comment]
okay, Thanks for support! 

Keep up the good work..
