### ISSUE TITLE
Help: Show bar chart value

### ISSUE THREAD

**Issue by quocthinh212** [diogobernardino/WilliamChart#103]
Hi,
i use your lib in my project but i can't find the way to show value of bar in barchart.
You can show it in your demo
![screenshot 4](https://cloud.githubusercontent.com/assets/14103334/12376177/a2e51824-bd19-11e5-983b-317e11cc2298.png)
Please help me.
Tks sir

**Comment by diogobernardino** [comment]
Just got that question recently, look at issue #102 .

**Comment by quocthinh212** [comment]
Tks sir. I had been found this solution.
But i have another question.
How to show threshold above barchart. But in curent it show below barchart.

**Comment by diogobernardino** [comment]
Perfect!

About your questions:
* Unfortunately you need to hack a bit to get the drawing order which fits your chart. I still need to come up with an idea for that, but so far I haven't thought about that. If you want to do it yourself check the method ```onDraw()```in ```ChartView``` class and do the:
```java
			if(!data.isEmpty())
				onDrawChart(canvas, data);
```
before:

```java
			// Draw threshold
			if (mHasThresholdValue)
				drawThreshold(canvas,
						getInnerChartLeft(),
						mThresholdStartValue,
						getInnerChartRight(),
						mThresholdEndValue);
			if (mHasThresholdLabel)
				drawThreshold(canvas,
						data.get(0).getEntry(mThresholdStartLabel).getX(),
						getInnerChartTop(),
						data.get(0).getEntry(mThresholdEndLabel).getX(),
						getInnerChartBottom());
```
This way you will get your threshold above the chart data.

* Not possible.

**Comment by quocthinh212** [comment]
And how to show Labels in 2 line (break newline): for example "Mon\n20/10" use \n for break new line

I have i trick for this funtion

Draw new chart below this chart with only YAxis bar lable, and set all values = 0, barchar hight = 10,
I will show text below this chart label :v:

**Comment by diogobernardino** [comment]
Good to know you found a way! Will consider this closed then.
