### ISSUE TITLE
Support for changing tooltip's text.

### ISSUE THREAD

**Issue by bhargavms** [diogobernardino/WilliamChart#105]
Would it be possible to add support to change a bar's tooltip text with maybe a custom value? Maybe create new variable called displayText in Bar class?

**Comment by diogobernardino** [comment]
You're the one defining the layout of your tooltip, you can add whatever text you want. Take a look at the Sample applications example.

**Comment by quocthinh212** [comment]
Please read following code:
Tooltip tooltip = new Tooltip(getApplicationContext(), R.layout.barchart_one_tooltip, R.id.value);
                TextView va = ((TextView) tooltip.findViewById(R.id.value));
                         va.setTypeface(Typeface.createFromAsset(this.getAssets(), "font/Roboto-Regular.ttf"));

                tooltip.prepare(areas.get(0).get(j), data.get(j) - (max / 9));

**Comment by diogobernardino** [comment]
I read it.

**Comment by bhargavms** [comment]
What is @quocthinh212   talking about?

**Comment by bhargavms** [comment]
@diogobernardino  I know that. But a tooltip is added to a chart as a whole instead of the individual bars, Basically my situation is this

 - I have a list, with a bhar chart as one of each list item's component. The display are for each bar chart is very small, therefore I cannot display any x Axis labels, what I instead would like to do is, show the x Axis label upon clicking a bar.

**Comment by diogobernardino** [comment]
As @quocthinh212 has put in his comment, you can keep the ```TextView``` object and then you can simply change its text when a bar is clicked (using ```OnEntryClickListener```). By changing it the tooltip should be displayed with the text you have just set.

**Comment by bhargavms** [comment]
oh alright thanks I was so stupid!
