### ISSUE TITLE
 as I do this layout?

### ISSUE THREAD

**Issue by uziassantosferreira** [diogobernardino/WilliamChart#107]
![screen shot 2016-01-19 at 4 35 08 pm](https://cloud.githubusercontent.com/assets/9255894/12429748/c2083d32-beca-11e5-8598-fa869418383a.png)

![screen shot 2016-01-19 at 4 35 04 pm](https://cloud.githubusercontent.com/assets/9255894/12429758/d6948dbe-beca-11e5-9d65-b9fc6f743a0a.png)

help me

**Comment by diogobernardino** [comment]
Did you look at the Sample Application code? You should have all you need there. You also have a javadoc.

(Note that you won't be able to show labels in the diagonal as you show in your second chart)

**Comment by uziassantosferreira** [comment]
Is it possible  use label above barchat ?

**Comment by diogobernardino** [comment]
No, that's not possible.

**Comment by uziassantosferreira** [comment]
ok, thanks for helping me.
