### ISSUE TITLE
Can i click between labels and labels area?

### ISSUE THREAD

**Issue by dnjfdbgid** [diogobernardino/WilliamChart#112]
i want to click linechartview between labels and labels area.
What should I do?

**Comment by diogobernardino** [comment]
Couldn't understand.

**Comment by dnjfdbgid** [comment]
![chart](https://cloud.githubusercontent.com/assets/7088793/12803150/b35486b6-cb2b-11e5-8135-6addfdfd3a3b.PNG)
Let's say in between the subjected two of x values, when I click the range or area, I would like to see the change/reaction with faded color marked. So that I could design the details, coming after accordingly. 
Thanks

**Comment by diogobernardino** [comment]
I'm affraid you won't be able to achieve that, not possible.

**Comment by dnjfdbgid** [comment]
Thank you for your answer.
