### ISSUE TITLE
onDetachedFromWindow() bug

### ISSUE THREAD

**Issue by narger17** [diogobernardino/WilliamChart#114]
Hello, i've managed to put your fantastic graph in a cardview and then the cardview in a recyclerview.
The problem is when the card leaves the screen, there the method onDetachedFromWindow() is called, and all the paints are cleared, though when the card returns in the screen, is crashed with an error

'long android.graphics.Paint.getNativeInstance()' on a null object reference

So I think that the paints should not be cleared on detach... What do you think ? thank you

P.s. sorry for bad english

**Comment by diogobernardino** [comment]
It seems the same as reported in #98 . I haven't had the time to look at it yet, but I want to.
