### ISSUE TITLE
High values causes chart block ui

### ISSUE THREAD

**Issue by aryaei** [diogobernardino/WilliamChart#115]
i tried drawing a chart that has float values that are around 1 million but ui gets blocked and nothing shows. i have checked everything and it seems values being high is the only reason because the second line works but first doesn't:

//private final float[] mValues = {100000.f, 200000.f, 140000.f, 400000.f, 350000.f, 430000.f, 200000.f, 400000.f, 600000.f};
    private final float[] mValues = {0f, 2f, 1.4f, 4.f, 3.5f, 4.3f, 2f, 4f, 6.f};

p.s: this is a great project i hope developer continues to develop it.

**Comment by XxPixX** [comment]
It gets blocked when creating the Y labels. You should set a step on the graph as the default step is 1.
If you only want the min and max Y values to be displayed then do 

`chart.setStep(max - min);`
