### ISSUE TITLE
Can you draw a graph to reverse?

### ISSUE THREAD

**Issue by wonnew1207** [diogobernardino/WilliamChart#119]
Hello,

First of all, Thank you for providing williamchart.

I want to draw the graph to the reverse.

![kakaotalk_20160321_102956298](https://cloud.githubusercontent.com/assets/16788128/13908947/de4df26e-ef50-11e5-89c1-e15c3dc575d8.jpg)

to

![1](https://cloud.githubusercontent.com/assets/16788128/13908893/422ec14c-ef50-11e5-8fce-3354e6f1cb9c.png)

I do not know because the novice developer.
Maybe, could you help?

**Comment by diogobernardino** [comment]
Not supported by the library.
