### ISSUE TITLE
Enhancement: BarSet from Array?

### ISSUE THREAD

**Issue by evanrich** [diogobernardino/williamchart#12]
I was just looking over the code I've got to generate a set of bars..

```
BarSet wins = new BarSet();     
        List<Integer> wins2 = null;
        try {
        wins2 = new GetHistoryArray().execute("wins").get();
        for (int j = 0; j < wins2.size(); j++) {

            Bar bar = new Bar(mMonths.get(j), wins2.get(j));
            wins.addBar(bar);
        }
    mBarChart.addData(wins);
```

This would be a heck of a lot easier to implement, if there was a method such as:

   BarSet wins = BarSetFromArray(wins2);

One line to generate the entire set.   I'm not super familiar with git, but I could probably fork the project, add this as a function in BarSet, but Java isn't my strength still, so maybe someone else can comment?

**Comment by sagits** [comment]
You can use Apache Commons:

 LineSet dataset2 = new LineSet(labels.toArray(new String[labels.size()]), ArrayUtils.toPrimitive(expenseValues.toArray(new Float[expenseValues.size()])));
