### ISSUE TITLE
X axis labels do not show when BarChartView height is set with percent support library?

### ISSUE THREAD

**Issue by KishorAndroid** [diogobernardino/WilliamChart#124]
X axis labels do not show when BarChartView height is set with percent support library?

The BarChartView shows properly when used this layout snippet
`<android.support.percent.PercentRelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    <com.db.chart.view.BarChartView
        android:id="@+id/barchart"
        chart:chart_setSpacing="8dp"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        chart:chart_barSpacing="8dp"/>
    </android.support.percent.PercentRelativeLayout>`

But when used with percent support library , X axis label are not visible
`<android.support.percent.PercentRelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    <com.db.chart.view.BarChartView
        android:id="@+id/barchart"
        chart:chart_setSpacing="8dp"
        app:layout_heightPercent="50%"
        app:layout_widthPercent="100%"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        chart:chart_barSpacing="8dp"/>
    </android.support.percent.PercentRelativeLayout>`

**Comment by diogobernardino** [comment]
I've tested the exact same layout you pasted and it all worked well. I played a little bit with percentages and other chart types and the library seems to be fully compatible with it.
