### ISSUE TITLE
Setting steps on the X axis

### ISSUE THREAD

**Issue by DanielKaparunakis** [diogobernardino/WilliamChart#127]
I tried to set the steps for the X axis & could not find a method to accomplish this task. I reviewed the source code as well & only found a method to set the steps for the Y axis. Could you point me in the right direction? Or is there no step method for the X axis?

Thank you.

**Comment by diogobernardino** [comment]
There's no concept of steps applied to X (of course unless you refer to an horizontal chart). In a vertical chart, X shows as many labels as you define in your set, there's no metrics behind that.

**Comment by DanielKaparunakis** [comment]
Right. In my case, I had 50+ data points, so I formatted the Y Axis & it looked fine. Since I couldn't format the X axis, since it is a vertical chart, the labels were not legible since there were too many so I hid them. Will you consider adding the option to create the step values for the other axis? or do you know a workaround in your library that I am not aware of?

Thank you again for your help.

**Comment by diogobernardino** [comment]
I see what you're after. No, I do not provide any method to make that happen. What you can simply do, and you may say it isn't a clean solution, which I agree, is to define the steps in the labels yourself by setting an empty string for the ones that should not be displayed.

**Comment by DanielKaparunakis** [comment]
I see. Thank you for your response, I'll leave the issue open in case someone wants to do a pull request or a fork and implement that.

Thanks for your time.

**Comment by diogobernardino** [comment]
I think the value you will get from having the library providing it as a feature it's not worth its implementation. I consider it too specific and at the same time too easy to implement on your own (as I described above). I will consider the issue closed for now.
