### ISSUE TITLE
Show Tooltip Whit Move Action

### ISSUE THREAD

**Issue by zhangsl** [diogobernardino/WilliamChart#128]
The library now show Tooltip when user click the point. But when there is a large data set, every point is small, it is hard to click. So can we check x or y value instead, not the point in region.

**Comment by diogobernardino** [comment]
Not sure I understood. What do you mean by xy value, the xy coordinate on the display, or the xy value of the chart? If you mean the second, you can simply set the listener which returns the index of both, set and value, and having that you the xy value of your chart.
