### ISSUE TITLE
Empty bars in BarChartView

### ISSUE THREAD

**Issue by eduardbosch** [diogobernardino/WilliamChart#130]
Hi!

First of all, thanks for this great library!

I want to report workaround that is not working in my case.

### Problem
I need to draw a BarChart with values of 0 and show the value of each bar at top of every bar. In case I have a set of values like [1, 0, 1, 2], I would like to see a result like this:
![should_see_this](https://cloud.githubusercontent.com/assets/3925897/15453144/0570132e-200a-11e6-98f5-e6728165a4bd.png)

Because values equals to 0 are not drawn, the result with default configuration, is this:
![value_0](https://cloud.githubusercontent.com/assets/3925897/15453147/139af806-200a-11e6-9519-4252ee51c277.png)

Then, if I forced values of 0 to be 0.0001, then I can see the space of the bar with 0 value (now 0.0001). But because de value is so tiny, when you get the entry rectangle _getEntriesArea(...).get(...)_, it's empty (width = height = 0) and the number tooltip is not being drawn.
![value_0 0001](https://cloud.githubusercontent.com/assets/3925897/15453150/3e7efa0e-200a-11e6-9c5f-1c2acb52425e.png)

Then, supose we change the values to [1, 0, 1, 502]. The bars of value 1 are near to be height 0 and if we change de values to [1, 0, 1, 1002], the difference between 1 and 1002 is so high that values with 1 are not drawn and entry rectangle is also empty.
![nearly_empty_regions](https://cloud.githubusercontent.com/assets/3925897/15453188/32eb0dd4-200c-11e6-9d50-9df9c4b0894e.png)
![empty_regions](https://cloud.githubusercontent.com/assets/3925897/15453190/354ce4da-200c-11e6-9d75-22e508623633.png)

### My solution:
I forked this repo and get a solution to my case:
- From my application I force all values of 0 to be 0.0001f in order that bar is being drawn by BarChart.
- To avoid having empty entries rectangles, I've modified _BarChartView.defineRegions_ method to force not creating empty regions by forcing a minimum height of 1 pixel always:
```
public ArrayList<ArrayList<Region>> defineRegions(ArrayList<ChartSet> data) {
	
	final int nSets = data.size();
	final int nEntries = data.get(0).size();
	
	ArrayList<ArrayList<Region>> result = new ArrayList<>(nSets);
	
	for(int i = 0; i < nSets; i++)
		result.add(new ArrayList<Region>(nEntries));
	
	float offset;
	BarSet barSet;
	Bar bar;
	
	for (int i = 0; i < nEntries; i++) {
		
		// Set first offset to draw a group of bars
		offset = data.get(0).getEntry(i).getX() - drawingOffset;

		for(int j = 0; j < nSets; j++){
			
			barSet = (BarSet) data.get(j);
			bar = (Bar) barSet.getEntry(i);
			
			if(bar.getValue() > 0)
				result.get(j).add(new Region(
						(int) offset,
						(int) bar.getY(),
						(int) (offset += barWidth),
						(int) this.getZeroPosition() + ((int) bar.getY() == (int) this.getZeroPosition() ? 1 : 0)));
			else
				result.get(j).add(new Region(
						(int) offset,
						(int) this.getZeroPosition(),
						(int) (offset += barWidth),
						(int) bar.getY() + ((int) bar.getY() == (int) this.getZeroPosition() ? 1 : 0)));
			
			// If last bar of group no set spacing is necessary
			if(j != nSets - 1)
				offset += style.setSpacing;
		}	
		
	}
	
	return result;
}
```
### Need to add this?

I think that will be really good to allow drawing bars with 0 values. Library can avoid "drawing" that bars to avoid wasting time on bars that are empty, but leave the space that should take that bars with value of 0 and force always to return non empty entry rectangles to allow adding tooltips to that bars.

Thanks again for all, and if I can help with something, let me know 😃

**Comment by eduardbosch** [comment]
Hi,

Is this solution a good solution to fix the problem I've found in my case? I don't know if this can break other things.

I'm using now a forked repository and I prefer to use your official repository to have the latest changes :)

Thanks a lot!

If you need more information, le me know please. Or if I could contribute in some way, let me know too.

**Comment by diogobernardino** [comment]
Thanks for the nice explanation.
I agree that every entry needs to have a Region associated, actually if not, the code might break in a different place. I will look at your code snippet and come up with a solution.
As for forcing values to 0.0001, I'm glad that worked for you but I would rather find something more solid as a fix. I will look into it.
I will post some updates here once I make any progress on this.

**Comment by diogobernardino** [comment]
Just pushed into ```dev``` branch the fix for empty regions. As I said, I believe the correct way is to force regions to exist, even when bar value equal to 0. In these cases regions are force to 1 pixel.
I've successfully tested this solution. I would be interesting to know if it correctly serves your specific case.

**Comment by eduardbosch** [comment]
Hi @diogobernardino !

Sorry for the long delay. I've been so busy and I didn't had time to check your fix in depth.

Now the space for the bars with 0 values are respected, so every bar it's at its correct place. That's great! 😃 

In the other hand, I'm still seeing a problem with some values that causes some entries to have 0 width and height.

Lib version: 2.4.0

If I use this values [1, 0, 0, 3, 0] or [1, 0.01, 0.01, 3, 0.01] everything goes well:
![screen shot 2017-01-13 at 09 48 51](https://cloud.githubusercontent.com/assets/3925897/21924444/803ca5da-d979-11e6-9369-a1f8731794cd.png)

But if I use some tiny values, then the entries regions of those tiny values has 0 width and height:
![screen shot 2017-01-13 at 09 51 24](https://cloud.githubusercontent.com/assets/3925897/21924466/96200af4-d979-11e6-855f-b5794d707d07.png)

The problem is that region is forced to have a minimum width/height when the value is 0, but no when it's tiny.

THANKS for all and this great lib 👍
