### ISSUE TITLE
Question about your chart/graph library

### ISSUE THREAD

**Issue by slobanthony** [diogobernardino/WilliamChart#131]
Hello,

I'm currently developing an Android application for a client that requires a certain chart mechanism.
While drawing charts within the application is a quite simple task, the problem is that we require the library that can place moveable markers on the charts them selves.
The example of what we need is in the attachment. 
The image shows only one, but we need up to 8 independent markers that can be moved with the finger. And they have to work absolutely smooth on a scale of 4096 values drawn on a chart. The implementation does not have to match the image, any kind of implementation is fine, as long as the result is what we need.
Basically we need multiple moveable markers, that can be moved left and right on the chart and fetch X value upon release.

Does your library support something like this?

Best Regards,
Slobodan
![hxcf3](https://cloud.githubusercontent.com/assets/19684206/15704335/82ae049e-27ea-11e6-8b14-869ae859ff6a.jpg)

**Comment by diogobernardino** [comment]
Not supported.
