### ISSUE TITLE
How can set animation LineChartView 

### ISSUE THREAD

**Issue by umeshbaldaniya** [diogobernardino/WilliamChart#134]
How can i animate  LineChartView graph as your demo2.gif 

please help me.
 
thanks..

**Comment by diogobernardino** [comment]
In demo2.gif I animate the LineChartView in very different ways, kind of randomly, is going to be difficult to get to know what was the customization you may want. I would give it a try to play with the API or maybe use the sample application (sandbox display), to take the first steps on it.
