### ISSUE TITLE
How can display data value?

### ISSUE THREAD

**Issue by taerran** [diogobernardino/WilliamChart#136]
I tried to max/min temperature(see screen shot) using StackBarChartView.

<img width="266" alt="screenshot" src="https://cloud.githubusercontent.com/assets/18208332/16220974/240f07b2-37cb-11e6-819a-a0c294668016.png">

How can display data value(29, 21 .....)?

thank you

**Comment by diogobernardino** [comment]
What you're showing is not a StackBarChart and the library doesn't support. It's neverthless a nice chart and a good idea.

**Comment by taerran** [comment]
Thank you for your comment. But, what I want to know is how to display data value in chart(see below screenshot : for example in LineChart, how to display 4.0 8.0 6.0 2.0 18.0 ?)
<img width="285" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/18208332/16231035/46c7ae38-37ff-11e6-85e0-34f3d7d66a8e.png">

**Comment by diogobernardino** [comment]
Understood. I do not provide it out of the box, but you should be able to achieve it using tooltips. 
The idea is to define one tooltip, which will have the data value, for each of the points displayed.

For instance, if you take a look at the third chart of the sample application (the purple/pink bar chart), you see the star poping up on top of the bar. Now imagine the same applied for each of the bars. Basically you want that but in a line chart.

**Comment by taerran** [comment]
Thank's a lot. I'll try.

**Comment by taerran** [comment]
Sorry for late answer.

I succeeded in showing data value. But, I can't be satisfied with my
working.(manually re-scaling axis range , because there are no room for
tool-tips....)
So, I still trying..

Thank you for sharing your library, and graceful comment.

2016-06-21 23:25 GMT+09:00 Diogo Bernardino <notifications@github.com>:
