### ISSUE TITLE
Improvement - supporting different background colors depending on vertical axis values

### ISSUE THREAD

**Issue by athkalia** [diogobernardino/WilliamChart#138]
Excellent library by the way, I really like the designer's touch in it !

Thinking about using this in an app, my question is whether there is a way to change the color of the background for specific parts the chart. 

E.g. if the vertical axis goes from 1 to 100, then I want the rectangular that exists for the whole chart under value 10 to be green and everything above it to have another color

Something like this: 
![example](https://cloud.githubusercontent.com/assets/6057808/16338985/ff6d2804-3a17-11e6-9d41-aefffba20f03.png)

**Comment by diogobernardino** [comment]
Thanks. No, you can only define a line has a limit, not a complete background.

**Comment by athkalia** [comment]
Thanks for the reply. Just of the top of your head, do you reckon that's something I can add easily in? Also would you be interested in a PR for this ?

**Comment by diogobernardino** [comment]
From the top of my head, looking at the code from the threshold limit already implemented it might be relatively decent to understand how to implement what you need.
About the PR, for now I would better mark this issue as an improvement (probably changing a bit the title as well) and see if more people feels the need for it. So far it hasn't been the case.

**Comment by athkalia** [comment]
Lovely, thanks pal.

**Comment by sidthakrey007** [comment]
hey do we have any zoom in zoom out support for this and to give height for axis

**Comment by diogobernardino** [comment]
No, not supported.
