### ISSUE TITLE
Show Grid

### ISSUE THREAD

**Issue by rutul089** [diogobernardino/WilliamChart#139]
How can I display GRID in LineChart?
I tried this but I don't know what should I put in PAINT.
`.setGrid(ChartView.GridType.FULL,Paint paint);`

I want this type of grid for my graph what shoud I do??
![grid](https://cloud.githubusercontent.com/assets/13690583/16558273/14e834a2-4202-11e6-8c80-e079d113ecc6.PNG)

**Comment by diogobernardino** [comment]
Paint class is provided by Android SDK, check the documentation.
https://developer.android.com/reference/android/graphics/Paint.html

**Comment by rutul089** [comment]
Thanks..
and I have also one more doubt. How to fix scale of X and Y axis 

 `  mChart.setBorderSpacing(Tools.fromDpToPx(1))
                .setAxisBorderValues(0, 500)
                .setYLabels(AxisController.LabelPosition.OUTSIDE)
                .setLabelsColor(Color.parseColor("#808080"))
                .setXAxis(false)
                .setYAxis(false)
                .setGrid(ChartView.GridType.FULL, paint);  `

I try this one but this is not working
![acs](https://cloud.githubusercontent.com/assets/13690583/16560145/24c4c57c-420f-11e6-944c-4809e8671113.PNG)

**Comment by diogobernardino** [comment]
You need to define a step using ```setStep(value)```.

**Comment by rutul089** [comment]
What is licence police for using this chart in my app???

**Comment by diogobernardino** [comment]
That info is at the end of the README file.
