### ISSUE TITLE
Improvement - supporting different value threshold on vertical axis

### ISSUE THREAD

**Issue by SergioCarabantes** [diogobernardino/WilliamChart#142]
Really love your library! animations are very cool. 

Only one question, in my implementation I would like to add more threshold, would it be possible?

Thanks man.

**Comment by diogobernardino** [comment]
Not sure if it serves your needs but you can define a start/end value for the threshold, which can give you the ability to display 2 lines. Do you require more than 2? If so, I'm affraid you cannot get it without hacking a bit the library.

**Comment by SergioCarabantes** [comment]
Yes, I require more than 3. Would you be interested in a PR for this?

**Comment by diogobernardino** [comment]
I've thought about how to implement it but unfortunatelly I haven't had the time so far. In case you're implementing it to fit your app then yes, feel free to pull it, I will check afterwards. Thanks

**Comment by diogobernardino** [comment]
Enhancement implemented (dev branch), should be part of the new release.
