### ISSUE TITLE
Scroll and pagination

### ISSUE THREAD

**Issue by alex-marochko** [diogobernardino/WilliamChart#143]
Hi. Thanks for your nice library.

Please, give me an advice - how can i add horizontal scrolling behavior like ViewPager has? Thanks for answer!

P.S. Sorry for my (possibly) bad English.

**Comment by diogobernardino** [comment]
Have you tried things like HorizontalScrollView?
Honestly I've never tried such cases, but I recall some people doing it. Maybe you can give it a try.

**Comment by alisherafat** [comment]
if you want a horizontal scroll behaviour you can set a large width size to your chart view like this:
` <HorizontalScrollView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fillViewport="true"
        >

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <com.db.chart.view.LineChartView
                android:id="@+id/chart1"
                android:layout_width="2000dp"
                android:layout_height="match_parent"
                android:layout_marginBottom="15dp"
                android:layout_marginLeft="20dp"
                android:layout_marginRight="20dp"/>
        </LinearLayout>
    </HorizontalScrollView>`

**Comment by alex-marochko** [comment]
@alisherafat , thanks for answer! You're right, but with this solution i got YAxis scrolling too (i want to fix it, it should be always visible). And, HorizontalScrollView gives me scrolling, but without 'paging': a want to show days grouped by weeks at XAxis, so after any swiping or dragging, when you release chart, you'll always see the whole week from Sunday to Saturday. I call this 'paging'.

One more solution that i've tried is setting many charts to ViewPager's pages, but this charts are separated one from other, i'd like to have continuous chart line.
