### ISSUE TITLE
Labels on Y axis are not drawn correctly

### ISSUE THREAD

**Issue by milen-3web** [diogobernardino/WilliamChart#145]
Thank you for you work and time spent on this great library! Could you please tell me how I can fix this issue:

![screen shot 2016-08-18 at 1 52 14 pm](https://cloud.githubusercontent.com/assets/7533241/17771384/4e8cb54a-654b-11e6-9793-79167029129d.png)

**Comment by diogobernardino** [comment]
Define the step between values with ```ChartView.setStep```. In future I intend to calculate a proper step depending on the values defined, but for now that's the way you have to workaround it.

**Comment by milen-3web** [comment]
Yes, now it works like a charm. Thank you very much!
