### ISSUE TITLE
BarChartView gets squeezed when device rotated!

### ISSUE THREAD

**Issue by sjd753** [diogobernardino/WilliamChart#147]
On rotation of device BarChartView gets either stretched (landscape) or squeezed (portrait). Using in fragment inside CardView and fragment being used in ViewPager.

**Comment by diogobernardino** [comment]
I couldn't reproduce it. Do you still have the problem?

**Comment by sjd753** [comment]
Yes! Use BarChartView in the fragment and use FragmentPagerAdapter for a viewPager.

**Comment by diogobernardino** [comment]
Can you provide a layout?

**Comment by diogobernardino** [comment]
As I cannot observe the same in any of my attempts to reproduce the problem, if there's no feedback from your side during the following week I will consider it a problem in your own layout and close the issue.
