### ISSUE TITLE
How to display specific number on touch?

### ISSUE THREAD

**Issue by tal32123** [diogobernardino/WilliamChart#148]
I was wondering how I can implement a feature where when I touch an area of the linechart it will show the specific value for that area. For context I am a new developer trying to develop a stocks app. So, I would like to have it show the price for the specific point in time when I click the chart.

**Comment by diogobernardino** [comment]
Do you want to show the number on top of the line entry, like a Tooltip, or do you want to get that number and then display in other completely different part of your layout? Looking at the sample application you may be able to find something similar implementations for both cases.

**Comment by tal32123** [comment]
Ahhh yeah I didn't know it was called the Tooltip! Thanks!
