### ISSUE TITLE
Add Skip x axis labels method for line chart

### ISSUE THREAD

**Issue by hammadtariqsahi** [diogobernardino/WilliamChart#151]
I am getting 30 days data for populating graph, I need to plot all points on graph but need to show only 5,6 labels on x axis. currently i am doing this with my own logic. i am adding "" after every six values. but my last value is not showing properly as I am sending 30 labels with graph data. 
there should be method which will skip values based on integer(5,6) out of total labels array.

**Comment by diogobernardino** [comment]
It never seemed nice to me that approach of having a skip method. Since this can be handle by passing "", unless I find out a better way of achieving it, I won't be providing such feature.
