### ISSUE TITLE
How to Set Horizontal Scroll in Line Chart 

### ISSUE THREAD

**Issue by sahilwebmazix** [diogobernardino/WilliamChart#152]
Using Line Chart i enable scroll bar using below code
 **linechart.setHorizontalScrollBarEnabled(true);**
 but i unable to see Scroll in Chart please help me if you have any code or method to set Scroll in Linechart the x axies values are merged not looking good i want to scroll the line chart in horizontal

**Comment by sahilwebmazix** [comment]
Any one can please help me ? if  there is any way to horizontal scroll in line chart ?
becouse there is mess Up of  X labels if more than 10-12 values

**Comment by diogobernardino** [comment]
Have you tried to use ```HorizontalScrollView``` defining a fixed ```width```?For the time being it's the only thing I can say. I will try to implement an example in the sample application in a future release.

**Comment by sahilwebmazix** [comment]
yes i tired but when i put line chart in Horizontal Scroll View  but when i used it it not displayed me chart 
my issue is X labels of chart are merged so i want a scroll so labels and chart are scroll horizontally   on screen
![screenshot_1475563542](https://cloud.githubusercontent.com/assets/22518814/19064682/6e507c80-8a2c-11e6-8a21-6adf91e61efc.jpg)

**Comment by diogobernardino** [comment]
You seem to be suffering from this #45 . Basically for some reason the view isn't calling ```draw``` method in certain big height/width. I already started looking into it but it will take me a while.

**Comment by sahilwebmazix** [comment]
Hey @diogobernardino  I Resolve this issue by Changing width & Height of LineChar Dynamically from Java Code  & Put This Chart in Horizontal ScrollView  Here is a code .

**XML Code** 
    `<HorizontalScrollView
        android:id="@+id/scroll_linechart"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:layout_marginBottom="45dp"
        android:layout_marginTop="15dp">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">
            <com.db.chart.view.LineChartView
                android:id="@+id/lineChart"
                android:layout_width="match_parent"
                android:layout_height="200dp" />
        </LinearLayout>
    </HorizontalScrollView>`

**JAVA Code**
`linechart = (LineChartView) rootView.findViewById(R.id.lineChart);
        scroll_linechart = (HorizontalScrollView) rootView.findViewById(R.id.scroll_linechart);
        DisplayMetrics displaymetrics = new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(displaymetrics);
        int width = displaymetrics.widthPixels;
/* set  only 8 values in  Window width rest are on sroll or dynamically change the width of linechart 
 is  window width/8 * total values returns you the total width of linechart with scrolling and set it in 
 layout Params of linechart .*/
        if (width < (mValues.length * width / 8)) {
            linechart.setLayoutParams(new LinearLayout.LayoutParams((mValues.length * width / 8),linechart.getLayoutParams().height));
        } else {
            linechart.setLayoutParams(new LinearLayout.LayoutParams(width, linechart.getLayoutParams().height));
        }`

**Comment by diogobernardino** [comment]
Those are good news. I will try to understand your code and see how can I apply it directly in ```ChartView```.

**Comment by sahilwebmazix** [comment]
yaa sure you can extend  My code in your setHorizontalScroll(boolean isScroll) method of   ChartView   code so this feature can work. you can dynamically add HorizontalScrollView in Chart Parent View like i did in XML

**Comment by diogobernardino** [comment]
After looking a bit more into it I think what you're doing isn't really solving the problem, you're just setting a smaller width which makes it work, however, if you set a smaller width in the xml chartview it will have the same effect. The question remains, why is the chart not display (I checked and the ```onDraw``` isn't called) once one defines a very big height or width.

**Comment by diogobernardino** [comment]
In order to have a single point of discussion it's better to continue the investigation in #45 and mark this one as duplicated.

**Comment by UsherBaby** [comment]
@diogobernardino  Have you fixed this problem ?

**Comment by UsherBaby** [comment]
Any plant to make ChartView scrallable ?

**Comment by haogg1996** [comment]
StackBarChartView not displayed because it is too large to fit into a software layer (or drawing cache), needs 8553600 bytes, only 8294400 available
