### ISSUE TITLE
Tooltip Images

### ISSUE THREAD

**Issue by icaboalo** [diogobernardino/WilliamChart#153]
Is there a way to set tooltip images dynamically depending on the value?

**Comment by diogobernardino** [comment]
I've never tried it but I would say yes, you should be able to set the source image of your layout view from the callback once an entry is clicked. You can find an example of a callback usage in the sample application.

**Comment by icaboalo** [comment]
Great, do you know in which part of the sample code can find the callback?
And I also have another question, I am using a lineChart that initially gets on set of data and number of labels, but when a button is pressed the number of entries and data changes completely but can't find a way to do it.

Java.lang.IllegalArgumentException: The number of entries between sets doesn't match.

That is the error I get when trying to do it normaly

**Comment by diogobernardino** [comment]
As an example, in ```BarCardTwo``` class I use ```setOnEntryClickListener``` to have a callback every time an entry is clicked.

You need to use ```reset``` method and rebuild your chart with the new number of entries.
