### ISSUE TITLE
Work with StackBarChartView

### ISSUE THREAD

**Issue by jac-usai** [diogobernardino/WilliamChart#156]
From source's documentation it's clear how to create a BarChart and work with it. Unfortunatly nothing is told about StackBarChartView.
I tried but i don't understand how to set multiple values for the same label.

**Comment by quocthinh212** [comment]
You can see here !
https://github.com/diogobernardino/WilliamChart/blob/6740c44e9fde95bc38f14df6dfceb8f0a1beaca7/mobile/src/main/java/com/db/williamchartdemo/stackedchart/StackedCardOne.java

**Comment by jac-usai** [comment]
I didn't see the samples.. Now I got it. Thank You.
