### ISSUE TITLE
onConfigurationChanged update

### ISSUE THREAD

**Issue by jac-usai** [diogobernardino/WilliamChart#157]
When device rotates the chart's parent changes his width, but the chart doesn't update. There is a way to force the chart to update?

**Comment by diogobernardino** [comment]
Seems related to #147. Can you provide more data like the layout and chart details?

**Comment by jac-usai** [comment]
#147 says the chart appear stretched or squeezed. In my case the chart maintains exactly the size that it had when the activity started. Is it normal?

**Comment by jac-usai** [comment]
This is my xml:
http://pastebin.com/LRAqvKKa

This is my onConfigurationChanged:
http://pastebin.com/01N0Y7E3

**Comment by jac-usai** [comment]
Any news?

**Comment by diogobernardino** [comment]
I have no problems using your layout structure. However, I can not assure it isn't something wrong with your `onConfigurationChanged`.
