### ISSUE TITLE
Linechart draws the line below the X-Axis

### ISSUE THREAD

**Issue by AruLNadhaN** [diogobernardino/WilliamChart#160]
When the values are zero then the chart content goes below the X-axis.

![chart](https://cloud.githubusercontent.com/assets/5804413/19762728/b31c04f4-9c58-11e6-9a4e-2ac8caff84c4.PNG)

These are the values used to plot the chart.

`    private final String[] mLabels = {"2016-09-02", "2016-09-05", "2016-09-10", "2016-09-10", "2016-09-02", "2016-09-05", "2016-09-10", "2016-09-10"};
   
private final float[][] mValues = {{0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f},
            {0f, 0.1f, 0.1f, 0f, 0f, 0f, 0f, 0f},
            {1.0f, 0f, 0f, 0f, 0f, 0f, 0f, 0f},};
`

**Comment by icaboalo** [comment]
Thats because you added the .smooth() attribute to true

**Comment by AruLNadhaN** [comment]
It works now. Thanks!
