### ISSUE TITLE
How to Show dot Values in LineChart 

### ISSUE THREAD

**Issue by sahilwebmazix** [diogobernardino/WilliamChart#163]
i added a dots in data set but its now showing current dot value in Chart. or ant way to show dot click show  their dot value ? 
` LineSet dataset = new LineSet(mLabels, mValues);
            dataset.setDotsColor(curr_activity.getResources().getColor(R.color.colorPurple))
                    .setDotsRadius(10f)
                    .setColor(curr_activity.getResources().getColor(R.color.colorAccent));`

**Comment by diogobernardino** [comment]
Not sure I fully understood it, but maybe what you need is to show the values somewhere around the values. If that's the case you can use tooltips for that, a good starting point would be to take a look at the first chart of the sample application.
