### ISSUE TITLE
Add Support for different Paints in Vertical i.e. Label and Horizontal i.e. Value Thresholds

### ISSUE THREAD

**Issue by muddassir235** [diogobernardino/WilliamChart#164]
I was using the WilliamChart library, specifically the line chart, and face a problem that I couldn't remove a threshold after adding one and couldn't specify different Paints for vertical and horizontal thresholds. I have fixed the Issue and would like to make a pull request :-). Just wanted to ask if you would this feature added :-).

**Comment by diogobernardino** [comment]
Good to know. It's indeed a nice to have. Do you believe is it worth to have it having into account the amount of code you implemented/changed? Maybe you can go ahead with the pull request, I will take a look at it for the next release. Thanks
