### ISSUE TITLE
Doesn't draw properly when chart is not in the front.

### ISSUE THREAD

**Issue by hwding** [diogobernardino/WilliamChart#167]
When the chart `show()` method is triggered in another fragment, then switch back to the chart fragment, the chart will always draw a single dot which is not the whole diagram.

**Comment by diogobernardino** [comment]
Can you try to elaborate a little bit more, I couldn't understand it. Not even sure to what are you referring to, might be the sample application, is it?

**Comment by hwding** [comment]
Sorry for my poor expression...  
There are four fragments in my app, all manipulated by tabs at the bottom. There will be a chart in one of these fragments, whose data sets are fetched from the internet.  
After pulling down to refresh this view, the app starts fetching data, then I switch to another fragment to see something else and wait for the result. At this point, the data finishes downloading then the chart is inflated and added to the container of the previous fragment.  
What should be noticed is that the chart's inflation is totally in the background.  So the problem **arises here**.
If I don't switch to another view and stare at this fragment until the chart is inflated and added, the chart will perform well.  

THE BUG IS LIKE: 
![screenshot_20161129-233600](https://cloud.githubusercontent.com/assets/15152879/20717427/615df38c-b690-11e6-83de-c7e88359f052.png)

IT SHOULD BE:  
![screenshot_20161129-233613](https://cloud.githubusercontent.com/assets/15152879/20717538/c58fc308-b690-11e6-9c94-11ce789acba9.png)

That means if the chart is not drawn in the fornt, the bug immerged.

**Comment by diogobernardino** [comment]
It seems to me that the parent view of the chartview is passing wrong height/width values as the fragment is still not yet measured. What I would try is to fetch your datasets but **only** show the chart on the moment this fragment is intended to be displayed. Does it make sense?

**Comment by hwding** [comment]
Yeah, I will try setting a viewTreeObserver on the parent view, tell you later if it works.
Thanks a lot :).

**Comment by hwding** [comment]
@diogobernardino It works! Thanks a lot! You are my saviour!
