### ISSUE TITLE
Changing between graphs?

### ISSUE THREAD

**Issue by rutul089** [diogobernardino/WilliamChart#170]
How can I swap between two same  type of graphs like [this](https://drive.google.com/open?id=0B74Xy-2lXAiuM3pfX1BYNFphT2c)  daily and weekly?

**Comment by diogobernardino** [comment]
You should be able to achieve this either by having 2 chart views, one on top of the other, or use only one and applying `reset` and re-building your chart every time you swap from daily to weekly.
