### ISSUE TITLE
Overlapping axis values

### ISSUE THREAD

**Issue by kirtan403** [diogobernardino/WilliamChart#171]
This image shows that my data values are overlapping:

![image](https://cloud.githubusercontent.com/assets/7900938/21226430/786c55c4-c2fb-11e6-9680-edb2d55fb6da.png)

However, I don't get overlaps for different type of data:

![image](https://cloud.githubusercontent.com/assets/7900938/21226482/abe3c248-c2fb-11e6-9b3d-8cfdc2a4dbe1.png)

Is there any configurations or something I can set this behavior?

**Comment by kirtan403** [comment]
Okay, I found it.

This solved it: 

```
chartView.setStep(15);
```

**Comment by diogobernardino** [comment]
Nevertheless, can you share the set of labels/values for which the chart was doing the overlaps?

**Comment by kirtan403** [comment]
@diogobernardino Sure, Here are the values:

For overlapping chart:
labels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
values: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 9.0, 12.0, 10.0, 12.0, 12.0, 1.0, 2.0, 3.0, 4.0, 7.0, 1.0, 29.0, 3.0, 7.0]

I hope this helps.

**Comment by diogobernardino** [comment]
I took a look and the thing is that when no border values (min and max) are defined the chart tries to come up with a nice scale finding the largest divisor of `max - min` which in this case (29 - 0 = 29) is 1.

**Comment by kirtan403** [comment]
@diogobernardino  I got your point. This can happen for a large number too. You can fix that by doing something like this (suggestion):

* Find the largest divisor, as you are already doing.
* If it is 1 ( and greater than 10 or something for larger values ), find `max / 2` and put it in between
* your scale will be `0`, `max / 2` and `max`

So there will be at least one middle entry and this issue will also be resolved.

**Comment by diogobernardino** [comment]
That way max / 2 can be a number with decimal places which should not happen.

**Comment by kirtan403** [comment]
@diogobernardino If you don't want floating values, than simply don't put steps on `divisor = 1`
