### ISSUE TITLE
Animation not working once updating an entry value to 0

### ISSUE THREAD

**Issue by kirtan403** [diogobernardino/WilliamChart#172]
I am really sorry to ask this silly question, but how can I update the data set for BarChart? I didn't found any documentation on this.

Currently, I am setting my data like this:

```
BarSet dataset = new BarSet(labels, values);   // labels is String[] and values is float[]
chartView.reset();
chartView.addData(dataset);
```

Now how can I update this data?

I have tried:

**1)**
```
        if (chartView.getData() != null)
            chartView.addData(dataset);
        else {
            for (int i = 0; i < values.length; i++) {
                chartView.updateValues(0, new float[]{values[i]});
            }
        }
        chartView.notifyDataUpdate();
```

**2)**

```
        if (chartView.getData() != null)
            chartView.addData(dataset);
        else {
                chartView.updateValues(0, values);
        }
        chartView.notifyDataUpdate();
```

What happens is, it starts adding multiple bars instead of updating current value and after-3-4 tries it crashes.

**Comment by kirtan403** [comment]
Ok, I found my mistake. Silly mistake. 

```
if (chartView.getData().size() == 0) {
            chartView.addData(dataset);
else {
            chartView.updateValues(0, values);
            chartView.notifyDataUpdate();
}
```

this worked perfectly.

But if new value is zero, it flickers. Means no animation for that. Just simply goes invisible in flash. That should not happen.

**Comment by diogobernardino** [comment]
Got it. It's fixed in dev branch.

**Comment by kirtan403** [comment]
@diogobernardino  Cool. When is the new version releasing?

**Comment by diogobernardino** [comment]
It might take a while as I still have a few things I would like to include before releasing.
