### ISSUE TITLE
Add a single point to highlight on line chart

### ISSUE THREAD

**Issue by kirtan403** [diogobernardino/WilliamChart#173]
I am preparing a line chart which shows some values for today. So, for today, the values will be available till current time, So, at current time I want to show a point, so the user can understand the data till this point is actual. And after this is the same as current or predicted one. Can I do that?

Or can I set the dashed line for some x values range and full line on the other?

**Comment by diogobernardino** [comment]
Check the first sample application chart.

**Comment by kirtan403** [comment]
I got it. Thanks 👍
