### ISSUE TITLE
Stop LineChartView from handling click

### ISSUE THREAD

**Issue by kirtan403** [diogobernardino/WilliamChart#174]
I have a line chart in the background. But, it prevents me from clicking anything which is over the LineChartView. I tried even setting an overlapping dummy view. Still clicking behavior on that region is not working. How can I stop LineChartView from handling clicks?

**Comment by diogobernardino** [comment]
As long as you don't set a `OnEntryClickListener` it won't.

**Comment by kirtan403** [comment]
@diogobernardino I haven't set any click listeners. Even if I add a dummy view on top of it, it is not working.

**Comment by kirtan403** [comment]
@diogobernardino One more note, I added the same `onClick` behavior (same function call) which I set for card view. Now, the only thing, which happens is, while the chart is animating, click is not working. After animation completes, click works. Something is wrong with the normal click behavior here.

**Comment by diogobernardino** [comment]
I will double check if for some reason the `LineChartView` is accepting clicks by default. Regarding clicks not working while animating, that's fine, it should be the case.

**Comment by kirtan403** [comment]
I tried using clickable=false, that didn't work. I also put a new view on top of it, still it wasn't clickable. 

That workaround will do fine for now.

**Comment by diogobernardino** [comment]
I can't see what you seem to be experiencing, enabled click without defining a listener or, another reason, without defining a `Tooltip`.

**Comment by kirtan403** [comment]
I am putting a chart in the background of a card view (background in the sense, using frame layout) and on top of it some content. When user click on the card it should start the new activity. But, the area covered by chart is not clickable. If you click anywhere outside the charview borders and inside the cardview, it is clickable (starts the new activity). But chart view is preventing me from clicking on top of it. Even if I placed a dummy transparent view on top of it using framelayout, still it as not clickable.

**Comment by diogobernardino** [comment]
Can you give me an example of layout where I can eventually understand and observe it?

**Comment by kirtan403** [comment]
Sure, Here is the layout:

         <android.support.v7.widget.CardView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:clickable="true"
                    android:focusable="true"
                    android:onClick="@{() -> handler.startNewActivity()}"
                    card_view:cardCornerRadius="4dp"
                    card_view:cardElevation="4dp"
                    card_view:cardUseCompatPadding="true">

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:background="?attr/selectableItemBackground"
                        android:clipToPadding="true"
                        android:orientation="vertical"
                        android:paddingTop="@dimen/activity_vertical_margin">

                        <TextView
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:layout_marginTop="5dp"
                            android:gravity="center"
                            android:text="Dummy Text"
                            android:textAppearance="@style/TextAppearance.AppCompat.Medium" />

                        <FrameLayout
                            android:layout_width="match_parent"
                            android:layout_height="150dp">

                            <com.db.chart.view.LineChartView
                                android:id="@+id/chart"
                                android:layout_width="match_parent"
                                android:layout_height="150dp"
                                android:onClick="@{() -> handler.startNewActivity()}" />

                            <RelativeLayout
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:layout_marginTop="10dp">

                                <TextView
                                    android:id="@+id/value"
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:layout_centerHorizontal="true"
                                    android:layout_marginTop="0dp"
                                    android:gravity="center"
                                    android:text='@{String.valueOf(value)}'
                                    android:textAppearance="@style/TextAppearance.AppCompat.Large"
                                    android:textSize="30sp"
                                    tools:text="1500" />

                                <TextView
                                    android:layout_width="wrap_content"
                                    android:layout_height="wrap_content"
                                    android:layout_below="@+id/value"
                                    android:layout_centerHorizontal="true"
                                    android:text="hi" />
                            </RelativeLayout>

                        </FrameLayout>

                    </LinearLayout>
                </android.support.v7.widget.CardView>

Note: This include the workaround of onClick on chart to make it work. Removing onClick from chart will make clicking not work over chartview.

**Comment by diogobernardino** [comment]
If you don't want the chart to listen on clicks why is it `android:onClick="@{() -> handler.startNewActivity()}` under `com.db.chart.view.LineChartView`?

**Comment by kirtan403** [comment]
I want the onClick event for the chart's parent FrameLayout. But, as chart captures the onClick events, as a work around I added onClick under ChartView.

I mentioned that in the bottom of the previous comment.

**Comment by diogobernardino** [comment]
Ok, I think I understand what's wrong. Looks like the chart view isn't passing the event click to the parent. I will look into it.

**Comment by diogobernardino** [comment]
This should solve your problem, let me know otherwise.
