### ISSUE TITLE
How to change LincChartView Point Dots

### ISSUE THREAD

**Issue by binaries10** [diogobernardino/WilliamChart#175]
How to change Dot state in LineChartView?
LineSet dataset = new LineSet();
dataset.addPoint(new Point("",1.0f); //Visible Dot
dataset.addPoint(new Point("",2.0f);//Invisible Dot

**Comment by diogobernardino** [comment]
`Point.setVisible()` should be what you're looking for, no?

**Comment by binaries10** [comment]
https://www.dropbox.com/s/j003u1bo2oqukxj/android-ldate.png?dl=0

LineSet dataset = new LineSet();
dataset.addPoint(new Point("",1.0f).setVisible(false); //InVisible Dot But show Line
dataset.addPoint(new Point("",1.0f).setVisible(false); //InVisible Dot But show Line
dataset.addPoint(new Point("",1.0f).setVisible(false); //InVisible Dot But show Line
dataset.addPoint(new Point("",1.0f).setVisible(false); //InVisible Dot But show Line
dataset.addPoint(new Point("",1.0f).setVisible(false); //InVisible Dot But show Line
dataset.addPoint(new Point("",2.0f);//Invisible Dot

**Comment by diogobernardino** [comment]
You're missing several parentheses in that code.
