### ISSUE TITLE
Float in axis border values

### ISSUE THREAD

**Issue by ArtemGorobets** [diogobernardino/WilliamChart#176]
Hi there. At first i want thank you for this great library. 
I'm faced with a problem: setAxisBorderValues method allows to work only with integer values. In my case i need to display values in the narrow range (for example between 0 and 1). So i have no ability to display row values: 0.1, 0.2, .. 1. I think ability to work with float values would be useful enhancement.

**Comment by diogobernardino** [comment]
Thanks. It doesn't support float/double values. Something I might think for the future, but definitely not soon.
