### ISSUE TITLE
Application Not Responding due to AxisRenderer.findBorders.

### ISSUE THREAD

**Issue by noiz354** [diogobernardino/WilliamChart#177]
Hello diogo, here williamchart getting **takes long time** which result **Application Not Responding**. i attach the code for test it. 

```
@Test
	public void findBorders(){
		int[] failed = {1012280,875350,1300730,0,0,0,2057040,0,0,0,0,0,0,0,0,633000,2328500,4269940,5779580,4834470,2780500,2121860,7479500,8195398,0,11985356,6708746,7217828,1116310,17202070,3139655,3656905,7640816,4088598,3595785,1318000,5227446,8126500,4465640,4494520,2849080,9347496,1140260,2666889,5723830,7035727,5474600,6739416,7016870,1668800,3985848,6105440,6451854,5107650,6798140,2616860,4841080,2269216,5057910,8562070,1385510};

		XRenderer mXRndr = new XRenderer();
		BarSet set = new BarSet();
		for (int i = 0; i < failed.length; i++)
			set.addBar(new Bar(Integer.toString(i), (float) failed[i]));
		ArrayList<ChartSet> mData = new ArrayList<>();
		mData.add(set);
		mXRndr.findBorders(mData, 9);
	}
```

maybe you could provide work around for this? thanks

after investigating when _max is 1.720207E7 and min 0.0_
then the while process will result application not responding. 

```
max = (max < 0) ? 0 : (int) Math.ceil(max);
		min = (min > 0) ? 0 : (int) Math.floor(min);
		while ((max - min) % step != 0) max += 1;

		// All given set values are 0
		if (min == max) max += step;
```

**Comment by diogobernardino** [comment]
I don't think it is getting in a forever loop but instead in a very long time, and that's due to the fact you're defining a very small step. 9 seems just a strange step for a range of values between 1.720207E7 and 0.0, isn't it?

**Comment by noiz354** [comment]
yeah, is there any workaround for that calculation ?

**Comment by diogobernardino** [comment]
Why don't you define a different step which makes more sense for your data?

**Comment by noiz354** [comment]
Right now, I skip the while process for searching step that makes different between max and min and also add some value to max to differentiate the value. But I hope this could have solve. By the way, thanks

**Comment by diogobernardino** [comment]
I still don't understand what do you mean by be solved, as it doesn't make sense to have a step of 9 in a range of values between 1.720207E7 and 0.0.

**Comment by noiz354** [comment]
here's take a look for my solution
