### ISSUE TITLE
How to change bar chart color ?

### ISSUE THREAD

**Issue by rutul089** [diogobernardino/WilliamChart#178]
Is it possible to change color of single bar as per reading ?
Photo link 
![device-2017-01-05-121426](https://cloud.githubusercontent.com/assets/13690583/21671516/e65b2f8c-d341-11e6-9aff-6eb09fb1fb68.png)

**Comment by diogobernardino** [comment]
`setColor`...?

**Comment by rutul089** [comment]
Like this 
![device-2017-01-05-121426](https://cloud.githubusercontent.com/assets/13690583/21672937/b630c2fe-d34b-11e6-9f77-b99b6a9a2f47.png)

**Comment by diogobernardino** [comment]
I understood. Isn't `setColor` enough?

**Comment by rutul089** [comment]
no

**Comment by diogobernardino** [comment]
because...

**Comment by rutul089** [comment]
I don't know but somehow this is not working 

`  BarSet barSet = new BarSet(mLabels, mValues[0]);
        barSet = new BarSet(mLabels, mValues[0]);

        //to set color between private and public
        if (isPublic) {
            //public
            if (mValues.equals(300)) {
                barSet.setColor(Color.parseColor("#72c16d"));
            }
        } else {
            //private
            barSet.setColor(Color.parseColor("#00B3BF"));
        }
        //  barSet.setColor(Color.parseColor("#72c16d"));

        mChart.addData(barSet);`

**Comment by diogobernardino** [comment]
Well, the code itself is correct, I'm only thinking whether that's the code you want.
Looking at the printscreen I would say you have only a single set, and what you want is to set a different color for each `Bar `in this `BarSet`, isn't it? If so, your code is wrong, you are applying the color to all bars in the set. Do `Bar.setColor(color)`, not `BarSet.setColor(color)`.

**Comment by diogobernardino** [comment]
Did you manage to achieve it?

**Comment by rutul089** [comment]
No

**Comment by diogobernardino** [comment]
I would really like to help but, in case you have corrected the code as I said in my previous comment, I have no other ideas about what to do, at the library level it works (you even have an example of that in the sample application).

**Comment by rutul089** [comment]
Yeah ,there is problem from my side , I already change code as u said .

**Comment by rutul089** [comment]
` BarSet barSet;
//        BarSet barSet = new BarSet(mLabels, mValues[0]);
//        barSet = new BarSet(mLabels, mValues[0]);
        barSet = new BarSet();

        Bar bar;
        for (int i = 0; i < mLabels.length; i++) {
            bar = new
                    Bar(mLabels[i], mValues[0][i]);
            Log.e("BarCard", bar.toString());

            if (0 <= mValues[0][i] && mValues[0][i] <= 50) {
                //good_map_marker
                bar.setColor(Color.parseColor("#6ecc58"));
            } else if (50 < mValues[0][i] && mValues[0][i] <= 100) {
                //satisfactory_map_marker
                bar.setColor(Color.parseColor("#bbcf4c"));
            } else if (100 < mValues[0][i] && mValues[0][i] <= 200) {
                // moderate_map_marker
                bar.setColor(Color.parseColor("#eac736"));
            } else if (200 < mValues[0][i] && mValues[0][i] <= 300) {
                //poor_map_marke
                bar.setColor(Color.parseColor("#ed9a2e"));
            } else if (300 < mValues[0][i] && mValues[0][i] <= 400) {
                //very_poor_map_marker
                bar.setColor(Color.parseColor("#e8633a"));
            } else if (400 < mValues[0][i] && mValues[0][i] <= 500) {
                //severe_map_marker
                bar.setColor(Color.parseColor("#d63636"));
            } else {
                //moderate_map_marker
                bar.setColor(Color.parseColor("#e8633a"));
            }


            barSet.addBar(bar);
        }`

**Comment by diogobernardino** [comment]
Is it actually entering in any of those if conditions? I have something very similar in one of the sample charts I provide, see [here](https://github.com/diogobernardino/WilliamChart/blob/master/mobile/src/main/java/com/db/williamchartdemo/barchart/BarCardTwo.java#L95).

**Comment by diogobernardino** [comment]
Can I consider this resolved?

**Comment by rutul089** [comment]
yeah Thnx for helping

**Comment by iSWORD** [comment]
Sorry for bumping an old thread but is this doable with the latest version?
