### ISSUE TITLE
Different tooltip for each dataset

### ISSUE THREAD

**Issue by tadeas-braun** [diogobernardino/WilliamChart#181]
Excuse me, if it is already possible, but it would be wonderful to set a tooltip to a dataset instead of the whole chart because I want each tooltip to have its respective color. Thanks in advance.

**Comment by diogobernardino** [comment]
You can use the `OnEntryClickListener` to get callbacks once an entry is clicked and, once it occurs you set the right color based on the set which was clicked, and tell the chart to show your tooltip. In the sample application, in the first linechart, I do something similar to show a tooltip once the animation finishes.

Something like:
```
// Just before this you can set the right color for your tooltip 
mTip.prepare(mChart.getEntriesArea(0).get(3), mValues[0][3]);
mChart.showTooltip(mTip, true);
```

Hope it helps.

**Comment by tadeas-braun** [comment]
Aaaah, sorry didn't notice that. Thanks a lot.
