### ISSUE TITLE
Step value must be a divisor of distance between minimum border value and maximum border value

### ISSUE THREAD

**Issue by thelong1EU** [diogobernardino/WilliamChart#182]
This is my code:
 ```
       mChart.setBorderSpacing(Tools.fromDpToPx(10))
                .setAxisLabelsSpacing(40)
                .setLabelsColor(getThisColor(context, R.color.colorAccent))
                .setGrid(numberOfValues, numberOfValues, gridPaint)
                .setValueThreshold(average, average, thresholdPaint)
                .setYLabels(AxisRenderer.LabelPosition.NONE)
                .setAxisBorderValues(min, max);
```

Why I'm getting this error? I don't set the step value.

**Comment by diogobernardino** [comment]
You could have easily traced it. That's probably being raised in `setAxisBorderValues(min, max)`. What are the `min `and `max `value?

**Comment by diogobernardino** [comment]
Is it clear now? Fortunately this exception won't be needed anymore in the next release as its only reason at the moment is due to the fact that only integer values are allowed as labels.

**Comment by thelong1EU** [comment]
Yes thank you so much. I really appreciate your work.
