### ISSUE TITLE
gettinf Index out of bound error 

### ISSUE THREAD

**Issue by sidthakrey007** [diogobernardino/WilliamChart#183]
It renders line chart properly bu after 10 sec app crashes checke LineChartView.java

Line 178			setSize = data.get(0).size();
			for (int j = 0; j < setSize; j++) {

				x = data.get(i).getEntry(j).getX();
				y = data.get(i).getEntry(j).getY();
				regions.get(i)
						  .get(j)
					

the first line should be setSize = data.get(i).size();

**Comment by diogobernardino** [comment]
I don't see any problem about having it `data.get(**i**).size()`, but the 0 shouldn't be a problem as long as you have the same number of entries per set (which needs to be always the case). Can you share the data where it is failing?

**Comment by diogobernardino** [comment]
Shall I disregard this?

**Comment by sidthakrey007** [comment]
yes i am doing that
