### ISSUE TITLE
How to Show Point Value in line chart ? 

### ISSUE THREAD

**Issue by sahilwebmazix** [diogobernardino/WilliamChart#185]

**Comment by diogobernardino** [comment]
Look at the examples.

**Comment by sahilwebmazix** [comment]
i saw in examples i didnot get any method to show Point Value  just Above the Point marked in chart.
if you have any idea please tell me which method of linechart is show points values

**Comment by diogobernardino** [comment]
The first chart in the sample app has tooltips showing an icon and value, in your case it will be only the value.

**Comment by diogobernardino** [comment]
In case you want your value to be shown without a click, see the method `showTooltip` in `BarChartOne`.

**Comment by sidthakrey007** [comment]
can i show value of point when point os clicked, also i want somw line parallel to x labels for dividing my graph is there any support for this

**Comment by sidthakrey007** [comment]
how can i show the point value when axis point is clicked in Line Chart View

**Comment by diogobernardino** [comment]
Again, check the sample application, class `LineChartOne`, I'm doing that there.

For the parallel line, I think what you want is `setValueThreshold` or `setLabelThreshold`, check those methods.

**Comment by sidthakrey007** [comment]
Thanks but dude that class is in your repo or where ? i cant find it.

**Comment by diogobernardino** [comment]
*`LineCardOne`

**Comment by tal32123** [comment]
I implemented an onclick which shows a toast with the value if it helps you here:

https://github.com/tal32123/StockHawk/blob/master/app/src/main/java/com/sam_chordas/android/stockhawk/ui/MyChartActivity.java

Hope it helps!!!

**Comment by sidthakrey007** [comment]
Thanks .!! dude linechart.setOnEntryClickListener This is what is was looking for  :) . You saved my day

**Comment by sahilwebmazix** [comment]
@sidthakrey007  hey can you please tell me how to show linechart   point values in chart ? 
using tooltip something in it ?

**Comment by sidthakrey007** [comment]
as i mentioned earlier you can use Linechart.setOnEntryClickListener , in this method you can build the tooltip right ??

**Comment by sahilwebmazix** [comment]
i don't know a way how to build a tooltip if you have a line of code to create tooltip on point can you share here @sidthakrey007  @tal32123

**Comment by sidthakrey007** [comment]
i cant find a way for Tooltip but you can work out with toast as tooltip requires a anchor view , and point in a graph for this chart is not a view , so i cannot be sure about that !!

**Comment by sahilwebmazix** [comment]
is there any way to show value Number with the point in LineChart  ?

**Comment by sidthakrey007** [comment]
yes i think tool tip can be supported . can you wait i ll be sharing the code to do that .because my requirement is also same to show tooltip , i ll be telling you today if i will succesful in that

**Comment by sahilwebmazix** [comment]
ok  Sure ,Thanks  :)

**Comment by sidthakrey007** [comment]
hello , i tried to show toast for point click for that i used OnEntryClickListener but its displaying toast when i click same point around 10-11 times, is it working properly?? or do i need to put that code over background thread??

**Comment by diogobernardino** [comment]
Do not duplicate questions across more than one issue. I'm considering this one answered.
