### ISSUE TITLE
Wrong bar height on update barchart values

### ISSUE THREAD

**Issue by eduardbosch** [diogobernardino/WilliamChart#186]
Hi,

I'm having issues with barchart bars sizes when I update the data values of a barchart. Looks like barchart maximum value might not be updated and barchart is not rendered correctly.

- If I use this values [1, 0, 0, 3, 0] and then I update the values to [1, 0, 0, 0, 0] the barchart draws correctly, because the maximum value has not changed:
<img src="https://cloud.githubusercontent.com/assets/3925897/23080141/05fdc1f8-f550-11e6-8d49-18faa7179912.png" width="600">

- If i set the values in the opposite order, then the maximum value increases from 1 to 3 and the bars does not have the correct heights:
<img src="https://cloud.githubusercontent.com/assets/3925897/23080142/05fde4da-f550-11e6-8eef-f5e8d77cc781.png" width="600">

----
To setup the barchart data every time I use this code:

> 
        // Update data
        chartView.dismiss(null);
        chartView.addData(value1, R.color.value1));
        chartView.addData(value2, R.color.value2));
        chartView.addData(value3, R.color.value3));
        chartView.addData(value4, R.color.value4));
        chartView.addData(value5, R.color.value5));

        chartView
                .setYAxis(false)
                .setYLabels(AxisRenderer.LabelPosition.NONE)
                .setXLabels(AxisRenderer.LabelPosition.NONE);

        // Show chart
        chartView.show(mAnimation);

I would like to create a test to show this issue, but I cannot compile the `dev` branch right now due to this commit 1dde4d76f6084c794a54a6f38a677c19d3574f05. I'm seeing this error:
> Error:(21, 0) Neither path nor baseDir may be null or empty string. path='null' basedir='**.......**/WilliamChart/mobile'

Thanks for all 😃

**Comment by diogobernardino** [comment]
I know exactly what you're referring to. Unfortunately this is something I'm aware since I first implemented the update-values-feature, and I take it as a current limitation as long as I do not find a pretty way of solving it. 
I know I could simply re-draw a new axis with new values but that would break the whole chart animation flow. In my opinion the correct way of doing this is by extending the animation support to both axis but so far I haven't reached an implementation I'm happy with.

**Comment by eduardbosch** [comment]
Is there any way to redraw the chart correctly without animating it right now? Or it is impossible to update values and redraw the chart correctly?

This is a feature I really need in my application. I'm thinking of deleting the entire view and create a new barchart from code. I know this is a really bad solution, but I need to update the data of the barchart and show it correctly.

About compiling, I'll define those variables or delete them. Thanks a lot 👍

**Comment by diogobernardino** [comment]
The option I see, even though not ideal, is to call `reset()` and build the chart again with the new data.

**Comment by eduardbosch** [comment]
I've changed the update code to this, but the problem seams to persist. Thanks for all your help.

```
        chartView.reset();

        chartView
                .setYAxis(false)
                .setYLabels(AxisRenderer.LabelPosition.NONE)
                .setXLabels(AxisRenderer.LabelPosition.NONE)
                .setAxisColor(color)
                .setBorderSpacing(Tools.fromDpToPx(8))
                .setTopSpacing(Tools.fromDpToPx(20));

        chartView.addData(value1, R.color.value1));
        chartView.addData(value2, R.color.value2));
        chartView.addData(value3, R.color.value3));
        chartView.addData(value4, R.color.value4));
        chartView.addData(value5, R.color.value5));

        chartView
                .setYAxis(false)
                .setYLabels(AxisRenderer.LabelPosition.NONE)
                .setXLabels(AxisRenderer.LabelPosition.NONE);

        // Show chart
        chartView.show(mAnimation);
```

**Comment by diogobernardino** [comment]
08267b83b59902a3add39e81c9ca41bd31818264 should solve the problem. 
Btw, you seem to be repeating some code above.

**Comment by eduardbosch** [comment]
I'll try tomorrow. Thanks for your support!

Yes, there is some repeated code just to make a quick test. I'll remove it.

**Comment by eduardbosch** [comment]
Thanks @diogobernardino! This works perfect now.

You are a MACHINE! 😃
