### ISSUE TITLE
OnEntryClickListener not working properly

### ISSUE THREAD

**Issue by sidthakrey007** [diogobernardino/WilliamChart#187]
i have used OnEntryClickListener in my fragment and on click i am supposed to show toast but it is showing one toast on 10 -11 clicks. do i need to do something additional like to run on background thread, or is there any additional condition for doing that ?? Please let me know for that !!

**Comment by diogobernardino** [comment]
Not sure I can understand, but it should work without any background thread. Try to do a printout in the `onClick` method and see if it triggers every time the point is clicked. Or maybe your clickable area is too small and you are not hitting it all the time, try to increase it with `setClickablePointRadius`.

**Comment by sidthakrey007** [comment]
ya clickable area was small sorry ,!! iam closing this issue.!! thanx for BIG help
