### ISSUE TITLE
Crash when setting new data

### ISSUE THREAD

**Issue by blackgin** [diogobernardino/WilliamChart#190]
Hi, I'm experiencing a crash in this situation:

1. Chart with single entry dataset
2. Try to replace the data

I'm experiencing the crash since v2.4.0

[Here](https://gist.github.com/blackgin/f4a13fb2c4cc9a4b264b5455ea086ed0) a gist that demonstrates the issue.

Maybe I'm doing something wrong, what's the correct way to replace current data?

Thank you!

**Comment by diogobernardino** [comment]
Use the _updateValues()_ following by _notifyDataUpdate()_. Note that you can only update data initially added. To add new data you will need to use _reset()_ and re-add the data.
