### ISSUE TITLE
LineChartView problem

### ISSUE THREAD

**Issue by liuzhanta** [diogobernardino/WilliamChart#196]
if value is { 0,0,0,0,1,1,1} , some part of x axis will be invisible

**Comment by diogobernardino** [comment]
Given your poor information I can't observe whatever you're observing. Do you intend to share anything else? Otherwise there's no point of raising an issue.

**Comment by liuzhanta** [comment]
You can use LineCardThree and change **mValues**
 `private final float[][] mValues = {{0f, 0f, 0f, 0f, 1f, 0f, 0f, 0f, 0f},
			  {1.5f, 2.5f, 1.5f, 5f, 4f, 5f, 4.3f, 2.1f, 1.4f}}`
Then you can see the problem.

**Comment by diogobernardino** [comment]
Still can't see any problem in `LineChartThree` while using those values...

**Comment by diogobernardino** [comment]
Maybe you can give 2.5.0 a try and see if you still experience the same.
