### ISSUE TITLE
Y axis showing incorrect data

### ISSUE THREAD

**Issue by Polyterative** [diogobernardino/WilliamChart#202]
I have a problem, when setting `			chartView.setYLabels(AxisController.LabelPosition.OUTSIDE);
` my Y axis shows all scale data, in addition to my desired values. In this case I have data from 1 to 100. The chart shows every number on Y (1.2.3.4....)
[Screenshot](http://imgur.com/a/WROqf)

How can I show only the correct value?

I need to quantize my Y values. I only want to show 3 or 2 of them (for example min and max Y values). 

[Tried using different array sizes](http://imgur.com/a/eIm1Q) (for labels and data), but library returns error:
`Arrays size doesn't match.`

**Comment by diogobernardino** [comment]
With `setAxisBorderValues` method you can define not just the min and max axis value but also the step between them.

**Comment by Polyterative** [comment]
Works perfectly, thank you so much!
[Leaving a screenshot of final result for future people passing by here](http://imgur.com/a/HmIRt)

Used `chartView.setAxisBorderValues(0, 100,20);`
