### ISSUE TITLE
IndexOutOfBoundsException in defineRegions()

### ISSUE THREAD

**Issue by joebroni** [diogobernardino/WilliamChart#203]
I am trying to use a BarChart inside of the first item in a RecyclerView (like a list header) and I am running into this error. It loads fine when the RecyclerView is first created but if I scroll until it is off the screen and try to go back, it crashes the app with this error. Any help you could give me would be great.

java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.get(ArrayList.java:411)
at com.db.chart.view.BarChartView.defineRegions(BarChartView.java:152)
at com.db.chart.view.ChartView$1.onPreDraw(ChartView.java:224)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1013)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2555)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7189)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
at android.view.Choreographer.doCallbacks(Choreographer.java:734)
at android.view.Choreographer.doFrame(Choreographer.java:670)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6776)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by diogobernardino** [comment]
Sounds similar to an old issue, I think. Give me the set of data you're using, I will take a look once I find the time.

**Comment by PDDStudio** [comment]
Why is this issue closed when it's not resolved?
I'm having the same problem right now. Is there any way to get rid of this error?

**Comment by diogobernardino** [comment]
If I don't get any feedback for several days I assume the user was the problem, not the library, and that's why I closed the issue.
Is there any set of data to reproduce it?

**Comment by PDDStudio** [comment]
I'm using `HorizontalChartBarView` in my custom view as shown below:

```java
public class WeaponStatsView extends RelativeLayout {

	private ViewWeaponStatsBinding binding;
	private BarSet barSet;


	public WeaponStatsView(Context context) {
		this(context, null);
	}

	public WeaponStatsView(Context context, AttributeSet attrs) {
		this(context, attrs, 0);
	}

	public WeaponStatsView(Context context, AttributeSet attrs, int defStyleAttr) {
		this(context, attrs, defStyleAttr, 0);
	}

	public WeaponStatsView(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
		super(context, attrs, defStyleAttr, defStyleRes);
		init();
	}

	private void init() {
		binding = ViewWeaponStatsBinding.inflate(LayoutInflater.from(getContext()), this, true);
	}

	private String getString(@StringRes int stringRes) {
		return getContext().getString(stringRes);
	}

	public void setData(Weapon weapon) {
		barSet = new BarSet();
		Bar power = new Bar(getString(R.string.weapon_details_power), weapon.getWeaponPower());
		Bar accuracy = new Bar(getString(R.string.weapon_details_accuracy), weapon.getWeaponAccuracy());
		Bar speed = new Bar(getString(R.string.weapon_details_speed), weapon.getWeaponContinuity());
		Bar recoil = new Bar(getString(R.string.weapon_details_recoil), weapon.getWeaponRecoil());
		Bar weight = new Bar(getString(R.string.weapon_details_weight), weapon.getWeaponWeight());
		barSet.addBar(power);
		barSet.addBar(accuracy);
		barSet.addBar(speed);
		barSet.addBar(recoil);
		barSet.addBar(weight);

		barSet.setColor(Color.parseColor("#00add7"));

		binding.weaponStatsChart.setBarSpacing(58);
		binding.weaponStatsChart.addData(barSet);

		int[] order = {4, 3, 2, 1, 0};
		binding.weaponStatsChart.setXLabels(XRenderer.LabelPosition.NONE).show(new Animation().inSequence(.5f, order));

		binding.weaponStatsChart.show();
	}

}
```

The View is used in my RecyclerView's Item. Binding the first 4-5 goes fine, but when I continue scrolling the app crashes with the same StackTrace as OP posted.

**Comment by diogobernardino** [comment]
Can you provide an example of a dataset (e.g. labels and values of a given `HorizontalBarChartView`)?
Because in the past I haven't been able to reproduce this just by placing several `HorizontalBarChartView `inside a `RecyclerView`. It worked.

**Comment by PDDStudio** [comment]
@diogobernardino I can give you access to the private repository where you can check and reproduce this error. So far I got it resolved by first calling `binding.weaponStatsChart.reset();` in `setData()`.
This seems to work fine as of now.

**Comment by diogobernardino** [comment]
That must have been exactly the problem, the fact you were not applying a `reset()` before adding new data.

**Comment by PDDStudio** [comment]
@diogobernardino As API consumer I wouldn't expect to be *forced* to call `reset()` when I know there wasn't any data added before. Can't this be handled by the Chart itself? If not I'd suggest adding this (quite useful/important) piece of information to the Docs.

**Comment by diogobernardino** [comment]
That's the point, if you're using a `RecyclerView `you might have data already since it is recycling/re-using views. 
It's part of the Wiki. In case you believe further important info should be added feel free to submit a PR.
