### ISSUE TITLE
Does WilliamChart LineChartView support displaying multiple line at the same time?

### ISSUE THREAD

**Issue by noiz354** [diogobernardino/WilliamChart#206]
Does WilliamChart LineChartView support displaying multiple line at the same time?

**Comment by noiz354** [comment]
such as like this, ![multiline21](https://user-images.githubusercontent.com/837457/27850866-7a179a58-6181-11e7-941c-89fd85826005.png)

**Comment by noiz354** [comment]
i take a look at https://github.com/diogobernardino/WilliamChart/blob/master/mobile/src/main/java/com/db/williamchartdemo/linechart/LineCardOne.java, and line 80 till 95 shows that it have 2 lineset. but it only shown one dataset. so, how do linechartview determine which dataset will be shown? Thanks

**Comment by diogobernardino** [comment]
In that sample I'm using the second lineset to update the values, not to present both at the same time.
There's is nothing special to be done in order to present more than one line, just give as many linesets as you want (using `addData()`)and then call `show()`.

**Comment by noiz354** [comment]
ok, got that, thanks
