### ISSUE TITLE
How to make the linechart horizontally scrollable?

### ISSUE THREAD

**Issue by Harish1729** [diogobernardino/WilliamChart#207]
The chart i am working has a lot of x-axis data.how can i enable the horizontal scrolling feature and what are the scrolling options? 
thanks in advance.

**Comment by diogobernardino** [comment]
You can use `HorizontalScrollView`, but be aware of #45, still to be solved.

**Comment by Harish1729** [comment]
Can you please elaborate on how to use it ? Is it enough if i add it in the layout or should i make any changes in the activity? I am really new to this stuff.

**Comment by diogobernardino** [comment]
You probably don't even need that extra `LinearLayout `, put `LineChartView` directly inside the `HorizontalScrollView`.

To set the min and max values you can use `setAxisBorderValues `method.

**Comment by Harish1729** [comment]
Thanks it finally worked . Great library by the way!
