### ISSUE TITLE
Barchart: How can i display corresponding bar values above or inside a bar?

### ISSUE THREAD

**Issue by Harish1729** [diogobernardino/WilliamChart#209]
How can i display corresponding bar values above or inside a bar?

**Comment by Harish1729** [comment]
How can i display corresponding bar values above or inside a bar?

**Comment by diogobernardino** [comment]
You should be able to handle that by displaying a tooltip for each of the bar chart entries. Take a look at the sample app, in one of the barcharts I display a tooltip on top of a bar, you can do the same for all of them.
