### ISSUE TITLE
Show all tooltips in same time

### ISSUE THREAD

**Issue by glnix** [diogobernardino/WilliamChart#210]
Hi.
I need show tooltip for every entry in same time.
Like this ![](https://habrastorage.org/web/cb2/85b/044/cb285b0445124054ab0b6338e3fadbad.png)

 How can i do it?

**Comment by diogobernardino** [comment]
Check the `BarCardOne` class, method `showTooltip()`. There I setup a tooltip for a specific entry, you can do the same for all of them.
