### ISSUE TITLE
Animation documentation outdated? setEasing not found

### ISSUE THREAD

**Issue by ardevd** [diogobernardino/WilliamChart#213]
So I've read through the animation documentation but the setEasing method doesnt seem to exist any more. Whats the replacement?

**Comment by ardevd** [comment]
Gotcha. I'll just look at the sample application from now on since the wiki documentation seems to be a bit outdated ;)

**Comment by diogobernardino** [comment]
You're right. I wanted to make a better version of it, smaller, and easier to maintain.
