### ISSUE TITLE
Gradle project refresh failed

### ISSUE THREAD

**Issue by Jayzh7** [diogobernardino/WilliamChart#217]
After I import the project in Android Studio
Gradle sync failed: Cause: path may not be null or empty string. path='null'
				Consult IDE log for more details (Help | Show Log)

**Comment by Jayzh7** [comment]
I deleted some of the gradle codes and it worked as a single project. If I import it as a module, deleting some codes still won't work.

**Comment by JAICHANGPARK** [comment]
I have same issue
Did you fix this?

**Comment by ubuntudroid** [comment]
I just attempted to import the project into Android 3.5 and while syncing stumbled upon the same issue:

```
A problem occurred evaluating project ':mobile'.
> path may not be null or empty string. path='null'
```

However there clearly is a path set in the according `build.gradle`:

```groovy
implementation project(path: ':williamchart')
```

@diogobernardino any idea what might be wrong here?

**Comment by ubuntudroid** [comment]
Okay, the fix turned out to be rather simple (although I had to restart Android Studio and sync manually before it was picked up by the IDE for some reason). Just add the following to the `local.properties` file so that the properties defined in the mobile `build.gradle` are set:

```
storeFile=""
storePassword=bla
keyAlias=bla
keyPassword=bla
play.accountEmail=bla
play.p12=""
```
