### ISSUE TITLE
I couldn't add it to Android studio!

### ISSUE THREAD

**Issue by Sathiyakugan** [diogobernardino/WilliamChart#219]
Please give me the demo or give clear documentation about it, please. Below one is the issue I got
https://stackoverflow.com/questions/46623427/interface-for-appcompatactivity-where-im-using-williamchart

**Comment by diogobernardino** [comment]
You don't need to extend CardController, I just created that class for my convenience. Just use any chartview as you would use any other android view.

**Comment by Sathiyakugan** [comment]
Could you please give me the link or explain how to add one of the charts from yWilliamChart and modify the values in my java class of android activity.

**Comment by diogobernardino** [comment]
There's nothing special about it, as long as you know how does a view work in Android.

1. Make sure you have a chartview in your xml layout
2. Use findViewById to get the chartview object in your Activity/Fragment
3. Use the chartview object to customize (e.g. add data) your chart through the API
4. Make sure you call `show` method once you're done customizing

**Comment by Sathiyakugan** [comment]
If I have a lot of data, it's not memory efficient to add all the data. I need to use listview and adaptor. Is WilliamChart supporting the drag view like listview that can be scrolled horizontally?

**Comment by diogobernardino** [comment]
No. You can achieve horizontal scroll with `HorizontalScrollView` but it won't manage elements as a listview.

**Comment by Sathiyakugan** [comment]
Thanks for the Support and replies I think my issue is resolved!

**Comment by Sathiyakugan** [comment]
```
<HorizontalScrollView
            android:id="@+id/garbageListView1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:fillViewport="true">

            <com.db.chart.view.LineChartView xmlns:chart="http://schemas.android.com/apk/res-auto"
                android:id="@+id/linechart"
                android:layout_width="match_parent"
                android:layout_height="100dp" />
        </HorizontalScrollView>
```
This code doesn't work! Please help!

**Comment by diogobernardino** [comment]
You will need to elaborate a need more...
