### ISSUE TITLE
Android Studio dependency

### ISSUE THREAD

**Issue by PJFonseca** [diogobernardino/WilliamChart#22]
Hello,

I was trying to put the dependency on Android Studio in the gradle file:
**dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
   compile 'com.db.williamchart:williamchart:1.0.0'
}**

And it gives me this error:
**Error:Failed to find: com.db.williamchart:williamchart:1.0.0**

Can you help on this?

Obrigado ;)

**Comment by diogobernardino** [comment]
Not sure if @TakilianRueshin comment has fully helped you, but if not, I would recommend you to take a look at some closed related issues.
