### ISSUE TITLE
Showing number of Y axis values displaying

### ISSUE THREAD

**Issue by kokilayaa** [diogobernardino/WilliamChart#220]
Can we limit the number of Y axis values displayed in the graph? I need only the lowest, highest and the medium value to be displayed on the Y axis in below graph.

![screenshot_20171025-185638 1](https://user-images.githubusercontent.com/25280592/32001248-e08386e8-b9b6-11e7-8450-da47dba2a9fd.png)

**Comment by diogobernardino** [comment]
If you can figure it out the lowest and highest value by yourself then you should be able to use the method below. Your `step `will be _highest + lowest /2_.

> public ChartView setAxisBorderValues(float minValue, float maxValue, float step)
> 
> A step is seen as the step to be defined between 2 labels. As an example a step of 2 with a maxAxisValue of 6 will end up with {0, 2, 4, 6} as labels.
> 
> Parameters:
> minValue - The minimum value that Y axis will have as a label
> maxValue - The maximum value that Y axis will have as a label
> step - (real) value distance from every label

**Comment by kokilayaa** [comment]
It worked. Thanks @diogobernardino ! Awesome library!
