### ISSUE TITLE
Wired animations when the axis border value is 0

### ISSUE THREAD

**Issue by kokilaw** [diogobernardino/williamchart#225]
I have implemented a bar chart view with minimum border value as 60. So the graph starts displaying values starting from 60. Sometimes there can be situation where a the value can be zero.

![img-0745](https://user-images.githubusercontent.com/25280592/34028432-1cf5da00-e189-11e7-9c28-7b6e59e345c3.jpg)

`show(Animation().inSequence(.5f)` makes the above weird animation in sequence from start to end. Picture took while the animation happening.

**Comment by diogobernardino** [comment]
If you define a minimum border value of 60, make sure not to pass values smaller than 60.

**Comment by kokilayaa** [comment]
But if the values are deviating only between like 80-90, I need to show the user the differences in a clear manner. When the minimum border value is set to 0, differences cannot be seen clearly. My use case is a blood pressure graph where the user needs to see how the values are deviating over the time clearly.
