### ISSUE TITLE
Draw line over the axis (minor tweak)

### ISSUE THREAD

**Issue by zoltish** [diogobernardino/WilliamChart#230]
See left edge of the chart - how the dot is slightly outside. Its not that big of a deal, but I think it would look better if it was drawn above (in elevation terms) the axis; or simply cut off so that all of it is inside the chart (I know this is harder to accomplish though).

Thanks :) 

![screenshot_1516352563](https://user-images.githubusercontent.com/4264531/35142876-087582b4-fd00-11e7-8967-05e1f4211086.png)

**Comment by diogobernardino** [comment]
In some cases this is actually better, so it was difficult which decision to take. If you would like to have axis under content you can fork the library and change the order that each one gets drawn in the `onDraw` method of the `ChartView` class.
