### ISSUE TITLE
Crash when resuming activity

### ISSUE THREAD

**Issue by zoltish** [diogobernardino/williamchart#231]
Navigating away from an activity and returning yields the following crash. The chart is inside a RecyclerView, if that makes any difference.

Let me know if you need any more info 👍 

`java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
    at com.db.chart.view.LineChartView.defineRegions(LineChartView.java:159)
    at com.db.chart.view.ChartView$1.onPreDraw(ChartView.java:224)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)`

**Comment by zoltish** [comment]
This also seems to happen whenever the dataset is refreshed more than once (also inside a RecyclerView).

**Comment by diogobernardino** [comment]
I'm doing pretty much that in the sample application and had no problems.

**Comment by zoltish** [comment]
Found the issue :) 

ChartView.addDataSet(lineSet) is being called on each onBindViewHolder() invocation. As a temporary workaround, calling .reset() just prior to it works; and if I understand your code correctly its (mostly/entirely) because the dataSet arraylist is re-created in the init() call then. It would be awesome to just have a setData() method, if thats a viable option of course.

**Comment by diogobernardino** [comment]
Version 2.x has been discontinued, I just published v3.0 completely rewritten from scratch but still with limited features.
