### ISSUE TITLE
Dual Slider

### ISSUE THREAD

**Issue by kksingla** [diogobernardino/WilliamChart#232]
I'm using this library, but unable to achieve the dual slider as shown in the image. Please help soon, it's urgent. Thanks
![34934776-c37a984e-fa01-11e7-96fd-8b01e2e56b3e](https://user-images.githubusercontent.com/18482328/36303425-1c937a10-1332-11e8-89d0-6e9efa552ce2.png)

**Comment by diogobernardino** [comment]
Does not provide such feature.
