### ISSUE TITLE
Line Chart Movable/Dragable when touch on a point on chart

### ISSUE THREAD

**Issue by nomizodiac** [diogobernardino/WilliamChart#236]
I want to implement a line chart exactly like shown in gif? Is there any callback where i can point where user has touch on linechart and then draw a marker on that point and then user can drag/move

![gcoj0](https://user-images.githubusercontent.com/3611309/38294436-42ad6d2c-3804-11e8-9a56-a510257d723d.gif)

**Comment by diogobernardino** [comment]
Not supported.
