### ISSUE TITLE
How to draw vertical line?

### ISSUE THREAD

**Issue by at-huynguyen3** [diogobernardino/WilliamChart#238]
How to draw vertical line like this?
Please help me!
![picture](https://user-images.githubusercontent.com/37994043/41138746-8d8c9e80-6b0d-11e8-9f82-ea2fc9f3faa5.png)

**Comment by diogobernardino** [comment]
Try using `ChartView.setGrid`.

**Comment by at-huynguyen3** [comment]
@diogobernardino not supported
it will look like: 
![screenshot_20180608-105944_1](https://user-images.githubusercontent.com/37994043/41283859-e96089b8-6e61-11e8-9c11-67c4846c9960.jpg)

**Comment by diogobernardino** [comment]
I see what you mean now. There's no easy way of doing that. You need to jump inside `LineChartView` and draw those lines in the `onDrawChart` method.
