### ISSUE TITLE
Unable to add dependency 

### ISSUE THREAD

**Issue by mahesh517** [diogobernardino/WilliamChart#240]
HI,
I am using 3.1 Android studio while adding dependency gettign error.
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.diogobernardino:williamchart:2.5.0.

**Comment by Hellogark** [comment]
Add it in build.gardle dependencies: implementation 'com.diogobernardino:williamchart:2.5.0', it worked for me
