### ISSUE TITLE
How do I show the values to right of the bars in a horizontal bar chart.

### ISSUE THREAD

**Issue by DanishAjaib** [diogobernardino/WilliamChart#241]
I was able to show a horizontal bar chart and remove all lines and borders. Setting the YLabel position to INSIDE makes it exactly as I wanted. There is only one I have been unable to do and that is to show the value of each bar to its right, inside or outside, either is fine. Is this possible?

**Comment by diogobernardino** [comment]
Version 2.x has been discontinued, I just published v3.0 completely rewritten from scratch but still with limited features.

**Comment by francescogatto** [comment]
Do you have some suggestions to see the ylablels in barchart?

**Comment by francescogatto** [comment]
i found it, just use this

 app:chart_axis="xy"
