### ISSUE TITLE
setSmooth(true) causes wrong max and min values

### ISSUE THREAD

**Issue by goemic** [diogobernardino/WilliamChart#247]
When LineSet.setSmooth(true) it draws a smooth line but the max and min value are exeeded. Thereby it shows incorrect values to the user.
![chart](https://user-images.githubusercontent.com/16276869/60891442-9e1efd00-a25d-11e9-93a5-e68bb7fb1e10.png)

**Comment by diogobernardino** [comment]
You may want to try v3.0 which was just published, let me know if the problem still persists. Please, take into account that it breaks compatibility with previous versions.

**Comment by cijo7** [comment]
I  think the issue still persists. I am using 3.7.2 and the y axis goes negative like the above screenshot when there are no negative values on setting smoothLine to true.
