### ISSUE TITLE
Will the documentation be updated anytime soon.

### ISSUE THREAD

**Issue by ardevd** [diogobernardino/WilliamChart#252]
Seems like the documentation on the wiki is  a bit outdated after your rework. Any chance for a refactored documentation any time soon? :)

LineSet / ChartSet doesnt seem to exist anymore for example.

**Comment by diogobernardino** [comment]
Thanks for the remind, completely forgot about that. I will probably just delete it and start something from scratch too.

**Comment by ubuntudroid** [comment]
@diogobernardino any idea when the new wiki will be live? Right now integrating the library with just what's in the README is not entirely straightforward unfortunately, but it looks oh so neat on the screenshot over there, that I just can't resist trying it out. ;)

**Comment by diogobernardino** [comment]
You're right, I feel bad I haven't yet spent enough time on that, I know I should. Though I can't tell a date, not even sure I want to use Github Wiki or some other docs platform. I'm now focused on adding donut charts to the list of charts supported, I will get back to the documentation after having that stable.

**Comment by robinpaulson** [comment]
Hi, we've been using v2.2 for a while in [Forecastie](https://github.com/martykan/forecastie/), but it appears that version is not supported any more so we're keen upgrade. We're struggling to implement v3.3, so those docs would be really useful. As ubuntudroid points out, the README is not quite enough. Cheers
