### ISSUE TITLE
Format y-axis labels

### ISSUE THREAD

**Issue by aglogger** [diogobernardino/williamchart#253]
Currently the labels i get on the y-axis of e.g. a line chart are like 5.93333334. Is there a way to display values like 5.90€ there?
And thanks for the library!

**Comment by diogobernardino** [comment]
Not yet, it's in the list though. Some sort of formatter which you could pass in to have labels formatted as you wish.

**Comment by ubuntudroid** [comment]
I'm working on a simple solution for this. PR inbound.

**Comment by wailbabou** [comment]
There is no information about it in the demo , even after @ubuntudroid commit ,
I think that we can use it like that now : 

` lineChart.labelsFormatter = { "${it.roundToInt()}" }`

**Comment by diogobernardino** [comment]
At some point it won't be feasible to show off all features in the demo App, so instead I decided it was time to invest on documentation. Still a working progress though, hopefully I will have something next month.

**Comment by krzdabrowski** [comment]
@ubuntudroid thanks for your fix. It helped a lot.

I found a small bug while implementing `LineChart`. I managed to modify a chart when clicking on it (and it draws with new data set) but unfortunately it doesn't redraw values on X and Y axes.

I think it should recalculate both values on axes (`LineChartRenderer`?) before it will be drawn with new data set (for example via `animate()`). Especially if chart itself can be dynamically modified (data set, gradientFillColors), but axes weirdly can't :)

Could you guys take a look at it?
And keep up the good work, I love your library!

**Comment by ubuntudroid** [comment]
@krzdabrowski Hm, I don't think it is directly related to this ticket. I think it would be better to create a new one.
