### ISSUE TITLE
Can't sync Gradle files after cloning

### ISSUE THREAD

**Issue by DarkMatterMatt** [diogobernardino/WilliamChart#256]
The changes you've added to the mobile app's `build.gradle` (I assume they're config files for `triplet.play`?) means that my Gradle syncs fail due to missing configuration files.

Could you please commit sample files so that other developers can test their contributions using the mobile app. I tried to find a way to only use config files for release builds but I wasn't successful.

**Comment by diogobernardino** [comment]
Good point. Need to think what's best to do, commit sample files or some different approach. I will tackle that in the next release.

**Comment by diogobernardino** [comment]
Should be fixed in this new release. Thanks for reporting.
