### ISSUE TITLE
How to set LineChart tooltip on every entry?

### ISSUE THREAD

**Issue by nicemak** [diogobernardino/williamchart#259]
Thanks for great library, I am using the latest library and i found out that a lot features from 2x are missing or i dont know how to use them as wiki is not updated.

how can i set touch events on entries and how can i show tooltips on every entry in linechart, barchart and horizontalBarChart?

Thanks

**Comment by diogobernardino** [comment]
Not supported by v3.x.

**Comment by ardevd** [comment]
Any plans on adding support for tooltips in v3.x?
