### ISSUE TITLE
Help :Sample Activity XML & Java code

### ISSUE THREAD

**Issue by Showkath** [diogobernardino/williamchart#260]
Hi ,
Thank you very much for implementing super library which i has animations in graphs.
This library is for Kotlin & Kotlin is an officially supported language to write Android but our app not implemented using Kotlin  . 
We would like to use graph library which has animations . X-axis & Y-axis would like to have Strings i.e in logic we will set Good, Avg, Bad in Y-axis based on calculations for each person (x-axis names like Test 1 , Test2...) 
Could you share example layout xml file & jaav code  .Can we use for this for below version

android {
 minSdkVersion 19
    compileSdkVersion 28
targetSdkVersion 28
}

Our build.gradle file has

allprojects {
    repositories {
        google()
        jcenter()

**Comment by diogobernardino** [comment]
What is exactly the problem you're having while using Java and the library?
