### ISSUE TITLE
Error with DonutChartView declaration

### ISSUE THREAD

**Issue by SemicolonIndia** [diogobernardino/williamchart#266]
Error at --> **This declaration is experimental and its usage should be marked with '@com.db.williamchart.view.ImplementsAlphaChart' or 'Use@Experimantal(com.db.williamchart.viewImplementsAlphaChart::class)'**

**val dcvReportChart: DonutChartView = layout.findViewById(R.id.dcvReportChart)**

here is my XML -->

 **<com.db.williamchart.view.DonutChartView
                android:id="@+id/dcvReportChart"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:chart_donutBackgroundColor="@color/colorApp"
                app:chart_donutRoundCorners="true"
                app:chart_donutThickness="16dp"
                app:chart_donutTotal="200" />**

What I'm missing here? Can you please help?
FYI, I am using it inside a PageAdapter of ViewPager. But the Error is still if I use it any Fragment or Activity.

**Comment by diogobernardino** [comment]
I decided to add as a precaution, to let people know that Donut Charts are a new addition to the library. Just add the annotation `@ImplementsAlphaChart` to your fragment, such as:

```kotlin
@ImplementsAlphaChart
class ThisIsYourFragment: Fragment() {
    // Your class
}
