### ISSUE TITLE
Cannot plot high values in LineChart

### ISSUE THREAD

**Issue by skadyrov** [diogobernardino/WilliamChart#27]
Values in Y axis are not plotted properly when they are high.

For example the following values are plotted like this:
{90f, 99f, 91f, 93f, 95f, 97f, 92f}
![device-2015-01-09-154033](https://cloud.githubusercontent.com/assets/2365058/5681424/cacdf350-9818-11e4-9b94-fc00966e291b.png)

And these are plotted as:
{115f, 99f, 91f, 100f, 101f, 130f, 105f}
![device-2015-01-09-153245](https://cloud.githubusercontent.com/assets/2365058/5681454/fcb278c8-9818-11e4-8bb6-f9b7c71fca77.png)

However, plotting low values works just fine:
{10, 3f, 1f, -1f, 11f, 8f, 1f}
![device-2015-01-09-161319](https://cloud.githubusercontent.com/assets/2365058/5681643/88c1c67e-981a-11e4-879f-0ebcd254420a.png)

Is this a bug? Or am I doing something wrong?

**Comment by diogobernardino** [comment]
Isn't it related with issue #23, and the fact that you're also using a positive minimum value for Y axis? If so, I got already a pull request with the fix that I need to review and merge it with the master. Either you apply the fix #25 yourself or you can get once I accept it.

**Comment by skadyrov** [comment]
Yes, it is actually the same issue. Didn't notice that.
