### ISSUE TITLE
Axis value update

### ISSUE THREAD

**Issue by Innomalist** [diogobernardino/williamchart#271]
Hello,
Thanks for great library, I have noticed there has been a new awesome update.
I remember in v2 there was a reset function which was required to call when we were updating chart values so the xAxis values would have been invalidated and recalculated on new call. How same thing can be achieved because on redraw (using animate function) I am having old xAxis values and updated chart is not displayed, I guess because some xAxis values of new dataset are larger than previous xAxis's maximum.

**Comment by krzdabrowski** [comment]
Hey @Innomalist , does my PR solve your problem?
https://github.com/diogobernardino/williamchart/pull/270

**Comment by Innomalist** [comment]
Hi @krzdabrowski,
I wanted to try but couldn't retrieve through jitpack (I can't remember, maybe it required some configuration in rep to work)
If you know a way other than downloading and importing that would make testing possible I'll be happy to test
I tried this and couldn't retrieve:
api 'com.github.krzdabrowski:williamchart:3.3.0'

**Comment by diogobernardino** [comment]
Available in `3.3.1`.
