### ISSUE TITLE
How to set min and max values for a LineChart?

### ISSUE THREAD

**Issue by kernelpanicsoft** [diogobernardino/williamchart#273]
![image](https://user-images.githubusercontent.com/32782870/76809033-240d2380-67af-11ea-87f1-73102d5abeb2.png)
I'm working on a blood pressure app, I need to set the min and max values labels for a Linechart, Is this possible?

**Comment by Kalianey** [comment]
Same problem here

**Comment by diogobernardino** [comment]
Is [scale](http://diogobernardino.github.io/williamchart/docs/chart.html#axis-attributes) what you're looking for?
