### ISSUE TITLE
label value can not update 

### ISSUE THREAD

**Issue by Icyrockton** [diogobernardino/williamchart#274]
When a new dataset is set, `label` value can not be updated .
![image](https://user-images.githubusercontent.com/42564541/80918873-aec6d380-8d99-11ea-81e3-1bf950117e9c.png)
![image](https://user-images.githubusercontent.com/42564541/80918889-c0a87680-8d99-11ea-91e0-f600b9b8a086.png)

so if we click the button , the bar value update ,but label value not update

**Comment by diogobernardino** [comment]
Seems like an issue fixed in `3.3.1`, could you try `3.4.0`?
