### ISSUE TITLE
DonutChart values and colors not corresponding 

### ISSUE THREAD

**Issue by axiel7** [diogobernardino/williamchart#280]
I set the values and colors in the same order but when I display the donut the last 3 values are inverted, also when I set the donutTotal to the sum of all values the DonutChart still have an empty space.

`This is my code:

    donutChart.donutTotal = 430F
        donutChart.donutColors = intArrayOf(
            Color.parseColor("#00c853"), // green
            Color.parseColor("#5c6bc0"), // blue
            Color.parseColor("#ffd600"), // yellow
            Color.parseColor("#d50000"), // red
            Color.parseColor("#9e9e9e") // gray
        )
        val donutSet = listOf(
            7F, // green
            346F, // blue
            13F, // yellow
            19F, // red
            45F // gray
        )
        donutChart.animation.duration = 1000L
        donutChart.animate(donutSet)`

`XML

    <com.db.williamchart.view.DonutChartView
            android:id="@+id/donut_chart"
            android:layout_width="200dp"
            android:layout_height="200dp"
            app:chart_donutBackgroundColor="@android:color/transparent"
            app:chart_donutThickness="22dp"
            app:chart_donutRoundCorners="true"/>`

The result:

![Screenshot_20200815-105517~2](https://user-images.githubusercontent.com/12379835/90309143-ec351400-dee5-11ea-9cf6-91e0a6f3e1ee.png)

**Comment by diogobernardino** [comment]
Just released a hotfix to tackle this issue, update your dependency to `3.7.2`.
