### ISSUE TITLE
Set decimals of Y-Axis values

### ISSUE THREAD

**Issue by kewitschka** [diogobernardino/williamchart#296]
How to limit decimals of Y-Axis values to 0?

`List<Pair<String, Float>> list = new ArrayList<>();
        list.add(new Pair<>("test",12364f));

        for (int i = 0; i < 10; i++) {
            list.add(new Pair<>("", 1500f));
        }
        list.add(new Pair<>("", 10000f));
        barChart.animate(list);

![Screenshot_20210222_160403](https://user-images.githubusercontent.com/12385342/108726658-f6386f00-7527-11eb-8fca-e129ef8b2aa3.jpg)

`

**Comment by joel-apollo** [comment]
Not well documented, but the solution is to do 
```chart.labelsFormatter = { "${it.roundToInt()" }```

You can also get fancy and do things like rounding:
```chart.labelsFormatter = { "${(it/100).roundToInt()*100}" }```
