### ISSUE TITLE
Move repository Jcenter to mavenCentral() 

### ISSUE THREAD

**Issue by CarlosVF2** [diogobernardino/williamchart#303]
Hi!

I've the question about if is possible to move the version 2.5.0 to mavenCentral. Link -> https://mvnrepository.com/artifact/com.diogobernardino/williamchart
Actually it's only other versions but not the version that we use, is it possilbe to move?

The reason about this change is the notice of obligation to migrate all repositories to mavenCentral. Link : https://developer.android.com/studio/build/jcenter-migration

Thanks in advance!

**Comment by diogobernardino** [comment]
Duplicate of #293

**Comment by diogobernardino** [comment]
I now see that I overlooked part of the description, I have no intention to migrate v2 to mavenCentral, only v3.
