### ISSUE TITLE
How to plot time chart?

### ISSUE THREAD

**Issue by skadyrov** [diogobernardino/WilliamChart#31]
I am trying to plot measurements taken on different days (not equidistant). However, I could not figure out how to plot the data based on time (or value). Please see the example below:

![device-2015-01-19-135102](https://cloud.githubusercontent.com/assets/2365058/5800879/ae20b246-9fe4-11e4-9f99-40f41626b604.jpg)

As you can see, all the values on the X axis are displayed with the same distance between them.
It would be great to create distance between the values on the X axis, based on their values. Are you planning to implement this support? Or any suggestions to to make this work? Thanks!

**Comment by diogobernardino** [comment]
That's not supported and I'm not planning to do it.
I would say you will need to modify method ``calcLabelsPos()`` in ``XController`` and do the math to place labels in the right coordinate.

**Comment by skadyrov** [comment]
I have a fix for this, I added an option to define the positions (indices) on the X axis, but it is not mandatory. So, it sets the distance between the items based on their index. I can provide a pull request  if you want.

**Comment by diogobernardino** [comment]
Go ahead, pull requests are always welcome. I will then review it and decide whether it should be merged or not. Thanks
