### ISSUE TITLE
How to avoid X axis labels and Y axis labels overlapping each other

### ISSUE THREAD

**Issue by skadyrov** [diogobernardino/WilliamChart#33]
I noticed that adding empty label (empty string) in the X axis labels helps to avoid overlapping of X and Y labels, however this does not work if I have a lot of data. Then this moves the X labels just a little bit, and I don't always know the amount of data to be plotted.
![device-2015-01-22-143732](https://cloud.githubusercontent.com/assets/2365058/5857227/457bb390-a24a-11e4-9a5b-050d513622d6.png)

Is there a way to avoid this overlapping? I thought of adding some space between the Y axis labels and the chart, but I couldn't find such a method implemented...

**Comment by diogobernardino** [comment]
You're right, there's currently no method for that. But as far as I remember, increasing the value of ´´axis_dist_from_label´´ in ´´library/res/values/dimens.xml´´ will solve you the problem.

**Comment by skadyrov** [comment]
That solved it, thanks :)

**Comment by holyspidoo** [comment]
I don't suppose there is a chart.setStep(integer) equivalent for X? We have to manage it manually when adding points (which easy enough, don't get me wrong)?

**Comment by diogobernardino** [comment]
Yes, you're right. X labels are taken straight from dataset input (as Strings), they're not manage in any way.
