### ISSUE TITLE
Vertical and Horizontal grids

### ISSUE THREAD

**Issue by skadyrov** [diogobernardino/WilliamChart#35]
I want to divide my LineChart into different sections, like below:
![device-2015-01-26-105951](https://cloud.githubusercontent.com/assets/2365058/5898239/b40dc4e6-a54d-11e4-88ba-0ae17b01aba9.png)

I tried using setHorizontalGrid and setVerticalGrid methods, but they just draw lines. And also, they draw lines for each entry (In my case, I would like to draw grid for multiple entries). And what would make it even better is adding an option to set the line labels on X axis for each Grid, centered, like in the picture.

How can I achieve such kind of result (or something close to that)? Any suggestions? Thanks!

**Comment by diogobernardino** [comment]
At the moment there's no way to support what you ask for. This looks like a very specific need. You can probably achieve it hacking ``draw*****Grid`` methods and applying a background to your LineChartView element in your .xml. But anyway, this is just a guess, you can perhaps find a better implementation.
