### ISSUE TITLE
Any way to Ylabel for minutes:seconds?

### ISSUE THREAD

**Issue by holyspidoo** [diogobernardino/WilliamChart#36]
Is there any way to have 1:00 1:30 ... etc. for y labels? For now I'm forced to use seconds and setmetric as "s", but I'd love to get a real time reading.

Maybe there is a  string override labels for y that I overlooked :) ?

**Comment by diogobernardino** [comment]
I'm not providing any way of doing it at the moment. What you can do is to hack a bit the ``draw``method of ``YController`` class and convert from seconds to the format you want when drawing the labels text.

Hope it helps. I will keep the idea as an enhancement though.

**Comment by diogobernardino** [comment]
Just pushed into dev branch the possibility to use DecimalFormat in order to format labels. Hope that helps you.
