### ISSUE TITLE
Gradient on LineChart and LineSet continues even if endAt is set

### ISSUE THREAD

**Issue by Syrou87** [diogobernardino/WilliamChart#37]
I updated the code in drawBackground in the LineChartView class to be this instead to fix it

        private void drawBackground(Canvas canvas, Path path, LineSet set, float minDisplayY) {

        float innerChartBottom = super.getInnerChartBottom();

        mStyle.mFillPaint.setAlpha((int) (set.getAlpha() * 255));

        if (set.hasFill())
            mStyle.mFillPaint.setColor(set.getFillColor());
        if (set.hasGradientFill())
            mStyle.mFillPaint.setShader(
                    new LinearGradient(
                            super.getInnerChartLeft(),
                            minDisplayY,
                            super.getInnerChartLeft(),
                            innerChartBottom,
                            set.getGradientColors(),
                            set.getGradientPositions(),
                            Shader.TileMode.MIRROR));

        //Check if we have changed end with EndAt, in that case reduce gradient and set it there
        if (set.getEnd() != set.size()) {
            path.lineTo(set.getEntry(set.getEnd() - 1).getX(), innerChartBottom);
        } else {
            path.lineTo(set.getEntry(set.size() - 1).getX(), innerChartBottom);
        }
        path.lineTo(set.getEntry(0).getX(), innerChartBottom);
        path.close();
        canvas.drawPath(path, mStyle.mFillPaint);
    }

If this is not a wanted feature, I think it should be an option atleast in WilliamChart, needless to say, I love WilliamChart :)

**Comment by diogobernardino** [comment]
Thanks for letting me know. I just fixed and pushed it to dev branch.
