### ISSUE TITLE
Hide or show line in line chart

### ISSUE THREAD

**Issue by johnjohndoe** [diogobernardino/WilliamChart#41]
Is it possible to toggle the visibility of the line between points in the line chart - I would love to see that?!

**Comment by diogobernardino** [comment]
I think you can achieve that, though not with a single method call.
What you can do is, imagining you want a ``LineSet`` that goes through points {A,B,C}, you need to create a ``LineSet`` for {A,B} and a ``LineSet`` for {B,C}, and then play with the ``show/dismiss`` methods (note that ``dismiss`` functionality still doesn't offer animation support).

**Comment by johnjohndoe** [comment]
Would be nice feature ...

**Comment by diogobernardino** [comment]
Indeed. But for the time being I will keep it as low priority.

**Comment by johnjohndoe** [comment]
Why are you closing a feature request that you are planning to implement in the future? Or did you mean you are **not** going to implement this function?

**Comment by diogobernardino** [comment]
I normally keep enhancements opened when I believe I might work on them in a near future, but I think this is not the case.
