### ISSUE TITLE
I cant seem to get LineChart to show

### ISSUE THREAD

**Issue by Zyg0te** [diogobernardino/WilliamChart#44]
Trying my best to implement a linechart in my app, however, no matter what I do I cant seem to get it to show at all. I am probably doing something wrong or missing some essential line of code, but here is my current code -> https://gist.github.com/Zyg0te/78921bc90c532b5cd3b8

Any input on what's missing would be most appreciated. The library seems awesome.

**Comment by Zyg0te** [comment]
I kinda solved this issue as well, but Im not sure how.

In the xml layout for the LineChart in the Sample app, layout_height is set to 0. If I set it something, say, 100dp, it shows up fine in my app, so Im guessing your sample app dynamically sets the height somewhere?

**Comment by diogobernardino** [comment]
The layout of the sample application has defined ```layout_weight``` for each chart, that's the reason for ```layout_height = 0```.

**Comment by Zyg0te** [comment]
Ah, that makes sense. Thanks!
