### ISSUE TITLE
can't import library using gradle

### ISSUE THREAD

**Issue by ZheKOs** [diogobernardino/WilliamChart#46]
I add to dependencies in <i>build.gradle</i> this  <code> compile 'com.db.williamchart:1. 7.0' </code> but I get such message: ![scr_28_02_2015_15_25_38](https://cloud.githubusercontent.com/assets/7936185/6426335/2da2fd92-bf5e-11e4-849b-41a7ea8f5abf.jpg) How can i handle this problem?
Btw same problem appears on some others libs.
I'm using <i>AndroidStudio 1.1.0</i>
Please help me. Thank You

**Comment by matbos** [comment]
You need to download the sources of this library, then open the cmd and type **gradlew install**
Then in you projects build.gradle add mavenLocal()
allprojects {
    repositories {
        jcenter()
        **mavenLocal()**
    }
}
Now you should be fine.

**Comment by ZheKOs** [comment]
Matbos, I change 
 <code>compile 'com.db.williamchart:1. 7.0'</code> 
to <code>compile 'com.db.williamchart:library:1.7.0'</code>
and add <code>mavenLocal()</code>
, but it still doesn't work.
![scr_28_02_2015_16_05_37](https://cloud.githubusercontent.com/assets/7936185/6426450/c03fb3ac-bf63-11e4-8c7f-985b2399d471.jpg)

**Comment by matbos** [comment]
Did you download source of this library and issued 
    gradlew install
?

**Comment by ZheKOs** [comment]
Yes, I downloaded source, but how should I use command <code> gradlew install </code>, because in windows CMD it says that it can't find such command.
![_28_02_2015_16_12_18](https://cloud.githubusercontent.com/assets/7936185/6426464/b490bfdc-bf64-11e4-9368-363aee07f2da.jpg)

**Comment by matbos** [comment]
You have to navigate to a downloaded source where the gradlew file exists and issue the command there.

**Comment by ZheKOs** [comment]
I run gradlew.bat and get this: ![default](https://cloud.githubusercontent.com/assets/7936185/6426533/abc8736e-bf68-11e4-8968-c4adf678495a.png)

**Comment by ZheKOs** [comment]
oh, I just add ANDROID_HOME and sdk.dir

**Comment by ZheKOs** [comment]
now there is now this problem, but terminal closes immidiatly and I can't type comand <code> install </code>

**Comment by matbos** [comment]
as well it should. Just open command line in the folder containing gradlew.bat and within that command line type gradlew install

**Comment by ZheKOs** [comment]
FAILURE: Build failed with an exception.
                            
* What went wrong:          
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.db.williamchart:library:1.7.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/db/williamchart/library/1.7.0/library-1.7.0.pom
         https://jcenter.bintray.com/com/db/williamchart/library/1.7.0/library-1.7.0.jar
         file:/C:/Users/Eugene/.m2/repository/com/db/williamchart/library/1.7.0/library-1.7.0.pom
         file:/C:/Users/Eugene/.m2/repository/com/db/williamchart/library/1.7.0/library-1.7.0.jar
         file:/C:/Users/Eugene/AppData/Local/Android/Sdk/extras/android/m2repository/com/db/williamchart/library/1.7.0/library-1.7.0.pom
         file:/C:/Users/Eugene/AppData/Local/Android/Sdk/extras/android/m2repository/com/db/williamchart/library/1.7.0/library-1.7.0.jar
         file:/C:/Users/Eugene/AppData/Local/Android/Sdk/extras/google/m2repository/com/db/williamchart/library/1.7.0/library-1.7.0.pom
         file:/C:/Users/Eugene/AppData/Local/Android/Sdk/extras/google/m2repository/com/db/williamchart/library/1.7.0/library-1.7.0.jar
     Required by:           
         TestWillianChart:app:unspecified

**Comment by ZheKOs** [comment]
I type command in my project dir not in lib dir.. now it is OK

**Comment by matbos** [comment]
Good to hear that!

**Comment by ZheKOs** [comment]
YEap. THANK YOU matbos :)
Everything is well right now (looks like :))

**Comment by ZheKOs** [comment]
And project finished without any problems! THANK YOU again!))
