### ISSUE TITLE
Change the color of a single or multiple dots

### ISSUE THREAD

**Issue by Lanzeroth** [diogobernardino/WilliamChart#47]
Hello, I was wondering if it is possible to change the color of a particular dot on the line chart.

**Comment by diogobernardino** [comment]
Good point, I think I missed it by the time I implemented Point object, I only covered that in Bar.
I will address that in the next version. In any case if you're in a hurry just look at the Bar class and implement the same for Point.

**Comment by Lanzeroth** [comment]
Oh, thats great!, thanks I'll look into it.

**Comment by diogobernardino** [comment]
I've separated completely Points customization. Now you will be able to customize (color, drawable image, size) either all Points in a LineSet or only a single one. I pushed the changes into the dev branch for now.

**Comment by Lanzeroth** [comment]
Nice! thanks for the quick implementation, much appreciated.
