### ISSUE TITLE
Cannot build with gradle

### ISSUE THREAD

**Issue by hyperh** [diogobernardino/WilliamChart#48]
I'm using Android Studio 1.1.0. I've been having some issues with building my project with this library. I added my ANDROID_HOME environment variable using the terminal in Android Studio.

    set ANDROID_HOME=C:\...\Android\android-sdk

So using the terminal I navigate to C:\\...\WilliamChart-master which contains the library source code I downloaded from github (the root directory where the gradlew file is).

And I managed to do installDebug properly.

    gradlew installDebug

But install doesn't seem to work

    gradlew install

I get the following errors:

    2 errors                                
    58 warnings                             
    :library:androidJavadocs FAILED         
             
    FAILURE: Build failed with an exception.
             
    * What went wrong:
    Execution failed for task ':library:androidJavadocs'.
    > Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): 'C:\...\WilliamChart-master\library\build\tmp\androidJavadocs\javadoc.options'
             
    * Try:       
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
             
    BUILD FAILED 

Here's my build.gradle (app)

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile 'com.android.support:appcompat-v7:21.0.3'
        compile 'com.doomonafireball.betterpickers:library:1.5.3'
        compile 'com.db.williamchart:library:1.7.0'
    }

Here's my build.gradle (Project)

    buildscript {
        repositories {
            jcenter()
            mavenLocal()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:1.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        }
    }

    allprojects {
        repositories {
            jcenter()
            mavenLocal()
        }
    }

**Comment by diogobernardino** [comment]
Can't really help you with that, @johnjohndoe was the one contributing with those gradle scripts. Perhaps you can check closed issues on that matter.

**Comment by johnjohndoe** [comment]
Sorry, I do not have the time right now. But I will look into this in a few days.

**Comment by johnjohndoe** [comment]
@hyperh Today I found time to investigate in the error you reported. The problem is caused because @diogobernardino [added a new Gradle script](https://github.com/diogobernardino/WilliamChart/commit/69db736e46405b96270f8d7a1ffa53f9b205a90d#diff-0d1d9100a9b6813b8cb5c470bf313d00R38) to deploy to Maven Central. This seems to conflict with the `install` task which deploys the library to your local Maven repository.

# Possible problem workarounds

1. The quick solution is to **temporarily comment out** the referenced line in the build script. The author is the only one anyways who will deploy the library to Maven Central.
2. If you are a user of the library not a developer then you have the other option to just **use what is available on Maven Central**. Once downloaded your local Gradle cache will hold the artifact to enable offline work.

**Comment by hyperh** [comment]
I'm probably going to be only a user of the library for now. I tried to import from Mavel Central but I got this: 
    
    Error:(25, 13) Failed to resolve: com.db.williamchart:library:1.7.0

Here's my new build.gradle (app)

    apply plugin: 'com.android.application'

    android {
        compileSdkVersion 21
        buildToolsVersion "21.1.2"

        defaultConfig {
            applicationId "com.myapp.myapp"
            minSdkVersion 15
            targetSdkVersion 21
            versionCode 1
            versionName "1.0"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile 'com.android.support:appcompat-v7:21.0.3'
        compile 'com.doomonafireball.betterpickers:library:1.5.3'
        compile 'com.db.williamchart:library:1.7.0'
    }

Here's my new build.gradle (Project)

    // Top-level build file where you can add configuration options common to all sub-projects/modules.

    buildscript {
        repositories {
            jcenter()
            mavenCentral()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:1.1.0'

            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }

    allprojects {
        repositories {
            jcenter()
            mavenCentral()
        }
    }

**Comment by johnjohndoe** [comment]
For some reason @diogobernardino changed the package name of the library as you can see on [Maven Central](http://search.maven.org/#artifactdetails|com.diogobernardino|williamchart|1.7.0|aar).

```groovy
compile 'com.db.williamchart:library:1.7.0'
```
vs.

```groovy
compile 'com.diogobernardino:williamchart:1.7.0'
```

**Comment by hyperh** [comment]
Ok that works! Thanks so much for the help! I'm pretty new to this Gradle and Maven stuff, so I didn't really notice that small change.

**Comment by hyperh** [comment]
I updated the wiki with your solution @johnjohndoe

**Comment by johnjohndoe** [comment]
You are welcome. Although changing the package name is a major change which should clearly be stated by @diogobernardino.

**Comment by diogobernardino** [comment]
The package name change seemed obviously necessary and indeed I was planning to add it to the wiki, my bad. Thank you guys.

**Comment by Muxagen** [comment]
Please update also the wiki. Thanks!
