### ISSUE TITLE
How to Show toolbar tip values without clicking bar in bar chart ?

### ISSUE THREAD

**Issue by Shanmugapriyan22** [diogobernardino/WilliamChart#49]
Hi, I want to show toolbar tip all the corresponding values in bar chart without clicking bar.

**Comment by diogobernardino** [comment]
Thanks for raising the issue, it might help other people.
As I told you before, in the meantime I've added the method ``ArrayList<Region> getEntriesRegions(int setIndex)`` (only in DEV branch for the time being) for those cases when you want to place tooltips without necessarily need to get a click event.
From that method you will get all regions matching each entry of a given set and then you're free to build your tooltip the way you want (as I do in the sample application for example).
I hope this answers your question. If not let me know.

**Comment by Shanmugapriyan22** [comment]
Thanks for the reply, Will check and let you know.

**Comment by Shanmugapriyan22** [comment]
Hi, Still i am confusing how to use that in bar chart ?
In updateBarChart() method how to use ArrayList<Region> getEntriesRegions(int setIndex) and show the values in bar.Can you please create sample for that ? It will helpful for me.Thanks.

**Comment by diogobernardino** [comment]
Have you looked, for example, at the method ``showBarTooltip`` in the sample application?
If I understood you correctly you will need something like:
```java
updateBarChart(){
	...
   	chart.show();
    regions = chart.getEntriesRegions(setIndex);
   	for(int i = 0; i < regions.size(); i++)
   		showTooltip(region.get(i))
}

private void showTooltip(Rect rect){
    // With the help of ``LayoutParams``you can set the position and size of your tooltip.
	LayoutParams layoutParams = new LayoutParams(rect.width(), rect.height());	
	layoutParams.leftMargin = rect.left;
	layoutParams.topMargin = rect.top;

	// The ``R.layout.tooltip``can take any shape you want (once again, you can see the 
	// tooltip xml examples in the sample application). 
	mBarTooltip = (TextView) getLayoutInflater().inflate(R.layout.tooltip, null);

	// Set the previous configured ``LayoutParams``to the inflated layout.
	mBarTooltip.setLayoutParams(layoutParams);
        
	// Pass the view to the chart
	chart.showTooltip(mBarTooltip);
}
```

**Comment by Shanmugapriyan22** [comment]
Hi here is the code based on your suggestion.

ArrayList<ArrayList<Region>> regions;
regions = mBarChart.getEntriesRegions(setIndex);
		for (int i = 0; i < regions.size(); i++)
			showTooltip(regions.get(i));

What's the value for set Index ? 

You created private void showTooltip(Rect rect){......} but in the for loop you created showTooltip(regions.get(i)).

**Comment by diogobernardino** [comment]
The meaning of ``setIndex`` should be also either described in the code or in the [Wiki](https://github.com/diogobernardino/WilliamChart/wiki) documentation, you should take a look. The ``setIndex`` is the index value of your dataset. As an example, in case you only have a dataset in your chart your setIndex will be 0.

Didn't get your last question.

**Comment by Shanmugapriyan22** [comment]
You created the following method to display tooltip.
private void showTooltip(Rect rect){...}

But inside the for loop you created the following method
showTooltip(region.get(i))

If i put setIndex value 0. I am getting error.

**Comment by diogobernardino** [comment]
Inside the loop I haven't created any method, I simply called the method ``showTooltip(Region)``.
If you get an error than you're doing something wrong. Remember that only can call the method getEntriesRegions after you instantiate your chart and show it. Feel free to post your error here.

**Comment by Shanmugapriyan22** [comment]
Hi,  there is no method for getEntriesRegions(set Index) in the chart view class.
Inside the loop you have called showTooltip(Region).You didn't create any method showTooltip(Region).

Where should i call the following method ?
private void showTooltip(Rect rect){
    // With the help of ``LayoutParams``you can set the position and size of your tooltip. 
    LayoutParams layoutParams = new LayoutParams(rect.width(), rect.height());  
    layoutParams.leftMargin = rect.left;
    layoutParams.topMargin = rect.top;
 
    // The ``R.layout.tooltip``can take any shape you want (once again, you can see the  
    // tooltip xml examples in the sample application).  
    mBarTooltip = (TextView) getLayoutInflater().inflate(R.layout.tooltip, null);
 
    // Set the previous configured ``LayoutParams``to the inflated layout. 
    mBarTooltip.setLayoutParams(layoutParams);
    // Pass the view to the chart 
    chart.showTooltip(mBarTooltip); 
} 

I am struggling for past 3 days.Please help me Very Thanks..

**Comment by diogobernardino** [comment]
Yes there is, I already told you twice that for the time being is only in *DEV* branch.

What I gave was a draft of code from the top of my head which you should understand, not just simply make a copy/paste. You're are struggling for 3 days and you couldn't figure it out that each ``Region`` object has a ``getBounds()`` method to return its ``Rect`` object? I'm really trying to help you, but you need to understand what you are doing before you actually do it.

**Comment by Shanmugapriyan22** [comment]
HI @diogobernardino  I am still not implement your chart.Can you please guide me ?
