### ISSUE TITLE
Bars has covered labels

### ISSUE THREAD

**Issue by kruil** [diogobernardino/WilliamChart#52]
Hi dev!
Is it possible to make a bars do not lay on labels? It covers labels now.
![image](https://cloud.githubusercontent.com/assets/6285203/7021679/071b759a-dd2d-11e4-8e9b-de45040c7ad0.png)
I was playing with opacity, but it seems that bars are forced to be always solid.

**Comment by diogobernardino** [comment]
You can use the method ``setBorderSpacing(dimen)`` to move bars to the right, away from labels.

**Comment by kruil** [comment]
Thank you for the fast answer. Unforunately I don't know how many letters is my labels, because its a money amount, so it different country to country. It can be just two, if I use euro, or ten, if I use Belarussian currency. So it will cost a pretty much space at right if I move it by border spacing. It should be pretty easy if bars will be allowed to get a transparency colors. Thank you for the great library.

**Comment by diogobernardino** [comment]
I see. Indeed the opacity would solve it, and in fact I would expect them to accept a hexadecimal with opacity. I will keep the issue opened and review that once I get the time.
Still going back to your problem, and looking at your (tiny) image, it seems to me that you're are setting Labels inside the chart, and that's why they get overlap with bars. Am I right?

**Comment by kruil** [comment]
Yes, label position is INSIDE now. That because different currency wants different spaces, as I wrote before. If I change it to outside, if there are Belarussian rubles, then labels will get about a half of screen width. Thank you.

**Comment by diogobernardino** [comment]
Right right. Then you really need bar with opacity. If not implemented, it should be something easy to have. I can let you know once I get a bit of time to recall the code.

**Comment by diogobernardino** [comment]
Got a chance to test it. In fact the alpha value (the opacity) works, the problem is, and that's something I should fix, when you use alpha in the animation as well, which I assume is your case. Right? If you don't define any alpha for the animation then you will get your bar with opacity.

**Comment by skr-sharma** [comment]
hi developer,

can you please elaborate how to set space in bottom(X-axis) linelabels from line.
i explore the library but unable to set space in lineLabels Array values.

**Comment by diogobernardino** [comment]
The only necessary customization can be done either using ``setTopSpacing(dimen)``, to set the outside border spacing of an axis, or using ``setBorderSpacing(dimen)`` to set both, outside and inside border of the axis. The spacing in between labels is then calculated automatically.

**Comment by skr-sharma** [comment]
hi developer,
thanks for reply...i appreciate your thought here i attached the two screenshots one is taken  from iPhone and another is from android in which i have  used your graph library(WilliamChart
)
i want to configure only two more  things:
1- space from bottom(betweeen first drawing  line and labelsString ) like ios screenshot
2- fill color to all the drawing point. if possible through your library please let me know i am stuck on this task last week.
![Uploading android_graph.jpg . . .]()
![Uploading iPhone_graph.jpg . . .]()



i am looking forward to response. thanks in advance

**Comment by skr-sharma** [comment]
![Uploading iPhone_graph.jpg . . .]()
![Uploading android_graph.jpg . . .]()


hi developer,
thanks for reply...i appreciate your thought here i have attached the two screenshots one is taken  from iPhone and another is from android in which i have  used your graph library(WilliamChart
)
i want to configure only two more  things:
1- space from bottom(betweeen first drawing  line and labelsString ) like ios screenshot
2- fill color to all the drawing point. if possible through your library please let me know i am stuck on this task last week.
i am looking forward to response. thanks in advance

**Comment by skr-sharma** [comment]
hi developer,
thanks for reply...i appreciate your thought here i have attached the two
screenshots one is taken from iPhone and another is from android in which i
have used your graph library(WilliamChart
)
i want to configure only two more things:
1- space from bottom(betweeen first drawing line and labelsString ) like
ios screenshot
2- fill color to all the drawing point. if possible through your library
please let me know i am stuck on this task last week.
i am looking forward to response. thanks in advance.

**Comment by diogobernardino** [comment]
There are no screenshots.

**Comment by skr-sharma** [comment]
hello developer..
thanks for reply, please check the above comment there i updated the Screenshot as well i want to make same as ios Screenshots have a look upon that.
any help will be appriciate...waiting for your response.

**Comment by diogobernardino** [comment]
1 - Use the normal android:paddingBottom in the xml.
2 - As stated in the [wiki](https://github.com/diogobernardino/WilliamChart/wiki/%283%29-Line-Chart), you have the method: ``setFill(color)``. 

Nice chart.

**Comment by skr-sharma** [comment]
Hello Diogober bardino,,

tone of thanks for your reply.....really i appreciate your work ,  as you guided in above comment  the   point two  method setFill(color) is working good.
still  i have problem with setting space...i used android:paddingBottom  but it took space from bottom but i want to set space between first y-axis line zero k  (i.e 0k)  and bottom Labels String values(same as ios screen) please have look of below screenshot  there i indicate space which i need to set in my app even i tried setTopSpacing(dimen) and .setBorderSpacing(dimen) but unable to achieve.

![image](https://cloud.githubusercontent.com/assets/12004449/7221255/0d5ae1ec-e701-11e4-8814-59266bc3ab64.png)

**Comment by diogobernardino** [comment]
I still have no method to set that, but though I have it abstract in a way that you can easily change that if you want. Look at the [AxisController](https://github.com/diogobernardino/WilliamChart/blob/master/library/src/com/db/chart/view/AxisController.java) class, line 121: 
``distLabelToAxis= (int) chartView.getResources().getDimension(R.dimen.axis_dist_from_label);``

So ``distLabelToAxis`` is the variable you would like to increase the value.

**Comment by skr-sharma** [comment]
finally it works welI , i  ought you my best thanks to you, For being supportive and understanding, gr8 work by  Diogober Nardilo keep it  :+1: :+1: :+1:  .
Please, accept my heartfelt Thank u...

**Comment by zakircoreconcept** [comment]
hi developer,
can you please elaborate how to set space between labels. I tried 
mChart.setAxisLabelsSpacing(20f); 
this increase the space between the line(X-axis) and labels, But how can i customize the label space.
Thanks.

**Comment by diogobernardino** [comment]
Unless you're missing a detail, what you're asking doesn't seem to make sense. Chart's width is always limited to the one you define in the layout and, the spacing between labels will always depend on that width against the number of labels you have defined in your chart.
