### ISSUE TITLE
Cant change the color of a single dot in lineChart

### ISSUE THREAD

**Issue by Angie-Ie** [diogobernardino/WilliamChart#53]
Hi, how to change single dots color in line chart? I want the start point and end point have different color. What i am already do 
private void updateLineChart() {
        mLineChart.reset();

        LineSet dataSet = new LineSet();
        for (int i = 0; i < lineLabels.length; i++) {
            dataSet.addPoint(lineLabels[i], lineValues[0][i]);
            dataSet.setDots(true);
            if (i == 0) {
               dataSet.setDots(true);
               dataSet.setDotsColor(this.getResources().getColor((R.color.horbar_grid)));
                Log.d("TAG", "masuk 3");
            }
        else
        {
            dataSet.setDotsColor(this.getResources().getColor((R.color.horbar_fill)));
            dataSet.beginAt(1);
        }
    }
        mLineChart.addData(dataSet);

![screenshot_2015-04-13-09-14-03 1](https://cloud.githubusercontent.com/assets/8733724/7108918/b8678958-e1bd-11e4-8c0d-33d1b4d2750c.png)

**Comment by diogobernardino** [comment]
I got that feature implemented ``Point.setColor(color)`` but it is still not in the MASTER branch. You can only find it in the DEV branch for the time being.

**Comment by Angie-Ie** [comment]
Thank you diogobernardio :)
