### ISSUE TITLE
Skip Point and more

### ISSUE THREAD

**Issue by calimero3986** [diogobernardino/WilliamChart#55]
Is it possible to make horizontal Labels (String[]) from 1 to 30 AND set the points to 2, 10, 12, 20 (e.g.)?
Or do i have to set the same String[]-Lenght for the Points and the Labels?
Or maybe i can set @null-Values to Skip the Points?

My LineChart should look like that:
![chart](https://cloud.githubusercontent.com/assets/1011832/7292359/af4ab0da-e99b-11e4-9b84-1f5227204a78.png)

**Comment by diogobernardino** [comment]
What you need is an X Axis accepting values instead of only indices/labels. This isn't supported by the library and I think it will be to difficult to find a workaround unless you go and dig into ``LineChartView`` class and hack it in order to get it working for your specific case.

**Comment by calimero3986** [comment]
Thank you for response.
Mhh. I will try to hack it on my own and let you know ;).

**Comment by diogobernardino** [comment]
I always try to comment everything the best as possible, I hope it is enough to get an understanding. 
Fine, I will keep the issue opened for the time being.

**Comment by calimero3986** [comment]
Perfect! Service/Support is great :), *Thumbs up*

**Comment by skr-sharma** [comment]
Hi developer..
its  my second query, first was successfully completed with your great support, i would like to thanks for that again.
![graph](https://cloud.githubusercontent.com/assets/12004449/7429635/5c3d4d0c-f022-11e4-9397-9931bcda20fc.jpg)


further what i want to configure your library that is  DotsStrokeColor for perticular X-axis lavel,  like if age <20 then it circleStroke color should be red , likewise for age 20 greater  and <60 it should be green.
and for remainning it should be white as it is now.
 if i tried this with your workarround methos dataSet.setDotsStrokeColor(this.getResources().getColor(R.color.reg))  from LineSet Activity class(line 116) 
public void addPoints(String[] labels, float[] linevalues) {

		if (labels.length != linevalues.length)
			Log.e(TAG, "Arrays size doesn't match.",
					new IllegalArgumentException());

		int nEntries = labels.length;
		for (int i = 0; i < nEntries; i++) {

			if (i == 0) {
				setDotsColor(mcontext.getResources().getColor(R.color.blue_bg));
				setDotsStrokeColor(mcontext.getResources()
						.getColor(R.color.red));
			}

			else if (i > 0 && i <= 60) {

				setDotsColor(mcontext.getResources().getColor(R.color.blue_bg));
				setDotsStrokeColor(mcontext.getResources().getColor(
						R.color.green));
			} else {

				setDotsColor(mcontext.getResources().getColor(R.color.line_bg));
				setDotsStrokeColor(mcontext.getResources().getColor(
						R.color.white));
			}

			addPoint(labels[i], linevalues[i]);

		}

	}

but i change circle color(first condition color) for all X-axis point not the specific. 
please find the attached screenshot,am looking forward to your response.

**Comment by BboyC** [comment]
Is the problem solved？

**Comment by diogobernardino** [comment]
Can u be more specific? What problem?

**Comment by BboyC** [comment]
Is it possible to make horizontal Labels (String[]) from 1 to 30 AND set the points to 2, 10, 12, 20 (e.g.)?
Or do i have to set the same String[]-Lenght for the Points and the Labels?
Or maybe i can set @null-Values to Skip the Points?

**Comment by diogobernardino** [comment]
No, what you're asking is not implemented. You always need to specify the same number of labels between datasets. What you can do, but I'm not sure it fits your needs or not, is to use ```endAt``` and ```beginAt``` methods in order to display only a subset of points. That is, imagine you have a dataset of 7 points but you only want to display a subset of them, between point 2 and 5, then you can do ```dataset.beginAt(1); dataset.endAt(4);```. Hope it helps.

**Comment by BboyC** [comment]
Thank you so much!
