### ISSUE TITLE
Changing chart's data while still animating causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by LukaszWiktor** [diogobernardino/WilliamChart#56]
I have a bar chart with variable number of bars. I enabled animations:
 ```
mBarChart.show(new Animation())
```
After that I noticed that it crashes when showing a chart with more bars than the previous one. It happens only if the previous animation hasn't ended yet.
![barchart-anim-crash](https://cloud.githubusercontent.com/assets/2964543/7721994/6edfb562-fedc-11e4-914a-4f8318a1adb5.gif)
The exception says:
```
java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
            at com.db.chart.view.animation.Animation.getUpdate(Animation.java:349)
            at com.db.chart.view.animation.Animation.access$100(Animation.java:33)
            at com.db.chart.view.animation.Animation$1.run(Animation.java:90)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```
Using the debuger I observed that `nEntries` was 4 (3rd chart has 4 bars) while `mInitTime` had only 3 elements (2nd chart has 3 bars).

**Comment by diogobernardino** [comment]
The library doesn't really support to increase/decrease the number of labels/values after you call ```show()``` for the first time. But perhaps you can get lucky with a method called ```reset()```. It basically resets the ```ChartView``` object to a default/clean state so you can add completely new data to it.

In any case perhaps if you show me a bit more of your code I can better tell you what you are or are not able to do.

**Comment by LukaszWiktor** [comment]
Hey @diogobernardino! Thanks for a quick response. Unfortunately, `reset()` is already there before `show()`. The full story that happens when I switch between charts in my app (1 ↔ 2 ↔ 3) is this:
```
    private void updateBarChart(int idx) {
        mBarChart.reset();

        Question question = surveyResult.getQuestions().get(idx);

        BarSet barSet = new BarSet();
        for (int i = 0; i < question.getAnswers().size(); i++) {
            Bar bar = new Bar(String.valueOf("abcdefgh".charAt(i)), question.getAnswers().get(i).getCount());
            bar.setColor(this.getResources().getColor(R.color.bar_fill));
            barSet.addBar(bar);
        }
        mBarChart.addData(barSet);

        mBarChart.setSetSpacing(Tools.fromDpToPx(3));
        mBarChart.setBarSpacing(Tools.fromDpToPx(14));

        int max = findMaxAnswersCount(question);

        mBarChart.setBorderSpacing(0)
                .setAxisBorderValues(0, max + (max % 2), 2)
                .setGrid(BarChartView.GridType.FULL, mBarGridPaint)
                .setYAxis(false)
                .setXLabels(XController.LabelPosition.OUTSIDE)
                .setYLabels(YController.LabelPosition.NONE)
                .show(new Animation());
    }
```

**Comment by diogobernardino** [comment]
Ok, I see it now, I missed the point about the previous animation not yet finished before you actually select a different tab. Now I know exactly the problem and it might have more than one solution that I will need to try out and release a fix in the next version.

A workaround for the time being will be that you introduce a stop() method in the Animation class which you will call in the reset() method. Kind of telling the Animation object to stop its work because you will introduce new data.

**Comment by diogobernardino** [comment]
Fix pushed to dev branch.
