### ISSUE TITLE
Unicode character in axis label

### ISSUE THREAD

**Issue by MJKhaani** [diogobernardino/WilliamChart#57]
Hi.Thanks a lot.
I've set Persian labels and it become question marks.
![Image of question marks](http://i59.tinypic.com/28vx1k0.jpg)
and this my labels in code:
```java
private  String[] lineLabels = new String[7];

private void intitLineLables() {
        String[] dayTitle={"یکشنبه","دوشبه","سه شنبه","چهارشنبه","پنجشبه","جمعه","شنبه"};
        Calendar cal = Calendar.getInstance();
        Calendar calendar = Calendar.getInstance();
        int day = calendar.get(Calendar.DAY_OF_WEEK);

        for (int i=6;i>=0;--i){
            --day;
            if(day==-1)
                day=6;
            lineLabels[i]=dayTitle[day];
        }
    }
```

**Comment by diogobernardino** [comment]
Wow! Thanks for letting me know. I will take a look and see how to solve it. Will include the fix in the next delivery.

**Comment by diogobernardino** [comment]
I quickly took a look at the issue and I'm wondering if this isn't solved by simply define a font which provides Unicode support. Are you using such a font?
