### ISSUE TITLE
Show Value Label on Line Chart

### ISSUE THREAD

**Issue by davidbin** [diogobernardino/WilliamChart#60]
Hi, I have tried every settings, but still could not find a way to show the value labels above the Data Point for Line Chart. Thanks.

**Comment by codebeautiful** [comment]
I'm also not found, Helps, Thanks.

**Comment by diogobernardino** [comment]
You mean, to have tooltips displayed for each entry point? If so, the current version isn't fully supporting that. I will soon (few weeks) release a new version which will also have a new sample application covering those cases I believe. I will keep the issue opened and notify once the new version is in place.

**Comment by codebeautiful** [comment]
beautiful ^_^

**Comment by diogobernardino** [comment]
I have pushed v2.0 into master branch with a completely revamped sample application. You should be able to take some example of code now (being more specific, you might want to look at the first Bar chart from the Bar chart display).
