### ISSUE TITLE
Not showing anything at all

### ISSUE THREAD

**Issue by Ph1b** [diogobernardino/WilliamChart#61]
I cannot get the library to show at all, it is always empty.

````java
BarChartView barChart = new BarChartView(this);
BarSet data = new BarSet();
for (int i = 0; i < 10; i++) {
    data.addBar(new Bar("bla", 1.0f));
}
barChart.addData(data);
chartContainer.addView(barChart);
````

**Comment by Ph1b** [comment]
Okay, it seems the view does not respect the layout params. If the height is set to WRAP_CONTENT, no view is shown

**Comment by diogobernardino** [comment]
I seem to remember to have that problem in the past but also to get it fixed. I will double check it once I have the opportunity. Thanks.

**Comment by diogobernardino** [comment]
No that I think a bit more about this, if you set WRAP_CONTENT how does the chart know what area shall it use? It's a bit of chicken and egg situation.

**Comment by Ph1b** [comment]
I think the app should specifiy a size for wrap content then in onMeasure. (When measureSpec is AT_MOST i guess). Have a look of the implementation of the SeekBar i.e. That's still visible. That makes it much less confusing as a developer to use the view.

**Comment by diogobernardino** [comment]
Nice. I've set a condition under onMeasure to cover those WRAP_CONTENT cases. 
Will include the change in the next version. 
Thanks for the tip.
