### ISSUE TITLE
Why repeats the last line

### ISSUE THREAD

**Issue by hknn** [diogobernardino/WilliamChart#63]
My problem is I repeated the last line. as follows.
![untitled](https://cloud.githubusercontent.com/assets/5147349/8583641/e65df942-25d7-11e5-8c62-386b3b5aadf2.png)

**Comment by diogobernardino** [comment]
Well, I wasn't really sure about the best approach so I ended up leaving it that way. The thing is, if you set a bigger border X spacing it might look better with that last grid line covering the whole chart area, however, I agree that when you have cases like yours it doesn't look that good. It would be good to get to know more opinions.

In the meantime I will keep the issue opened and I will let you know in case I do something about it.

**Comment by diogobernardino** [comment]
I've implemented a different way of handling this. Now you will be able to set the number of rows/columns you would like to have drawn in your grid. I believe the approach solves not just this but also other problems.

I've pushed it into the dev branch already, will be included in the next version afterwards.
