### ISSUE TITLE
Can we show realtime data in LineChart. 

### ISSUE THREAD

**Issue by vijayrawatsan** [diogobernardino/WilliamChart#65]
- Basically I want to update(append) more values in linechart. Is this possible?

**Comment by diogobernardino** [comment]
No, this isn't an available feature. And honestly I do not expect to have it implemented any time soon.

**Comment by navidei** [comment]
I'm implementing something similar in this way:
1. Start a thread using android handler to update my ChartSet, which is a accessible by main thread and the new one. In the new thread I use handler.postDelayed(Runnable, 1000) to update data in the next second.
2. After updating data I send a message to handler.
3. In the handleMessage method I dismiss data of chart and again give the data to it and call show().

**Comment by vijayrawatsan** [comment]
Thanks for replying. It won't help me now but someone can benefit from it.
