### ISSUE TITLE
Is it possible to specify a number of data to be visible while using horizontal scrollbar

### ISSUE THREAD

**Issue by weejim76** [diogobernardino/WilliamChart#67]
Hi,
Thanks for the nice library.
I am using BarChartView and am only planning to display 10 bars at a time due to mobile device screen  constraints.

I have setHorizontalScrollBarEnabled(true) on the BarChartView, but are there any methods that I can call to restrict the number of visible bars on the screen?
For e.g. the barSet has 50 bars but I would like to show the last 10 bars on the screen while giving the users the ability to scroll horizontally to the first 40 bars.

Jim

**Comment by diogobernardino** [comment]
There's no functionality in the library to get to know that.
