### ISSUE TITLE
 update some values , meanwhile update YAxis Label when chart is showing

### ISSUE THREAD

**Issue by yinpeng633** [diogobernardino/WilliamChart#68]
I want to update some values , meanwhile update YAxis Label when chart is showing"

I try it by invoking notifyDataUpdate(), it doesn't work, notifyDataUpdate() should  support only values.

I try it by invoking setAxisBorderValues() and setStep(), then chart.show(),
but it take a long time to show the chart.  
How can I shorten the time?

Thank you!

**Comment by diogobernardino** [comment]
The update values functionality assumes that those new values will fit the current Y axis scale. At the moment the library isn't support the update of Y axis scale while updating values.

Indeed it seems a good-to-have, however, I can't foresee an easy way of doing it specially if you want to have animation effects while changing the scale. I will keep it in mind as a future implementation but still, something far away to get implemented at the moment.
