### ISSUE TITLE
Set Dots missing

### ISSUE THREAD

**Issue by douglasd3** [diogobernardino/WilliamChart#69]
Can't find dataSet.setDots(boolean).

I checked the class and this method is missing, how can i set a dot on a LineChartView?

**Comment by diogobernardino** [comment]
That's part of the model class LineSet. Just style your Dots with setDotsXXX methods and they will be displayed.

**Comment by douglasd3** [comment]
I have tried:

lineSet.setColor(Color.parseColor("#FF58C674"))
                .setDotsStrokeThickness(Tools.fromDpToPx(2))
                .setDotsStrokeColor(Color.parseColor("#FF58C674"))
                .setDotsColor(Color.parseColor("#eef1f6"));

I get this from the exemple code, yet the dots are not been displayed (only the line is been colored). Am i missing something?

**Comment by douglasd3** [comment]
I just figured it out, i was setting the dots customization methods before adding the points, now i'm setting the customization after and its working just fine.

Thanks for the help!
