### ISSUE TITLE
Unable to set margin,Xaxis value(s) partly visible 

### ISSUE THREAD

**Issue by Dokuzov** [diogobernardino/WilliamChart#73]
Hi i have a chart which uses months of the year as an Xaxis. My point is doesn't matter if i set the height to wrap content , fixed dp value , or match parent , neither of android:gravity nor android:marginBottom works but you can see on the image[1] that , well see Apr , for example letter P is half visible and so are some of the others.

Any workaround please?

Soruce:
[1] http://i.imgur.com/m9jO4yS.jpg

**Comment by diogobernardino** [comment]
Seems something to be fixed. Will take a look once I have the time. In the meantime I believe you can workaround it with a padding bottom, can't you?

**Comment by Dokuzov** [comment]
I thought i have tried , but anyway now added some paddingBottom and it made it through, thanks.

**Comment by diogobernardino** [comment]
Perfect. Anyway I would like to cover those cases automatically so I will keep the issue opened for now.

**Comment by diogobernardino** [comment]
Fixed in dev branch. Will be part of next version.
