### ISSUE TITLE
LineChart Fill and Hidden Grid problem

### ISSUE THREAD

**Issue by cederom** [diogobernardino/WilliamChart#74]
Hello and thank you for this nice library!

I am implementing LineChart with some charts that are filled. This causes lowest filled chart to cover my grid. How can I add lines with fill that would allow to show the grid below the charts?

Does Fill exclude Grid??
<img width="336" alt="screen shot 2015-09-06 at 13 18 16" src="https://cloud.githubusercontent.com/assets/3051832/9704078/94b2481e-5499-11e5-867e-aacc02e67436.png">

**Comment by diogobernardino** [comment]
You need a completely change in the order of which the various chart elements are drawn, and I must tell you it is a very specific order.
Basically at the moment I'm drawing the grid and then the linesets (which includes the fill) on top. From what I understand you need to draw in the following order: fill, grid, and finally linesets. 
In case you really want to go that away you need to dig into [``ChartView``](https://github.com/diogobernardino/WilliamChart/blob/master/library/src/com/db/chart/view/ChartView.java) class and [``LineChartView``](https://github.com/diogobernardino/WilliamChart/blob/master/library/src/com/db/chart/view/LineChartView.java), and modify this order under ``onDraw`` and ``onDrawChart`` methods, respectively. Alternatively, you may want to play with the alpha of your fill color in a way that it can still allow you to see your grid in the background.

**Comment by cederom** [comment]
Thank you for fast reply :-) I am not sure if order can help as bottom part of the fill still covers the grid. I have already drawn charts in reverse order. data.setFill(Color.TRANSPARENT); and data.setAlpha(0.0f); / data.setAlpha(1.0f); did not change anything.

I think the only way to do this would be to draw fill not straight to the X axis line, but up to the line below..?

Also I don't see the possibility to draw lines with fill and with no fill at the same time (i.e. Color.TRANSPARENT)..?

Thank could be very nice change and feature :-)

**Comment by diogobernardino** [comment]
Have you hacked the methods ``onDraw`` and onDrawChart`` as I said, and still, you didn't manage to achieve? That's strange...

**Comment by cederom** [comment]
Ah, not there, will do, and report back :-)

--
CeDeROM, SQ7MHZ, http://www.tomek.cedro.info
