### ISSUE TITLE
Set new limits when calling updateValues()

### ISSUE THREAD

**Issue by orensharon** [diogobernardino/WilliamChart#75]
I have a list of values, clicking on an item updates the graph (by calling updateValues(...) and notifyDataUpdate() right after).

I want to set new limits before each update of the graph (using setAxisBorderValues(0, newMax, 1) ).

**Comment by diogobernardino** [comment]
That's not supported at the moment. You can achieve that by re-instantiating your xml chart object with the new values and borders.

**Comment by orensharon** [comment]
I have tried that, but the animation is much better when using update.
Any chance to keep the nice animation with your solution?

**Comment by diogobernardino** [comment]
Not really :(
