### ISSUE TITLE
How to achieve real-time dynamic chart use WilliamChart？

### ISSUE THREAD

**Issue by aimicm** [diogobernardino/WilliamChart#76]
Did WilliamChart  can support for achieving a dynamic chart ?What should I do？

**Comment by diogobernardino** [comment]
Real-time data chart not supported.

**Comment by navidei** [comment]
I'm implementing something similar in this way:
1. Start a thread using android handler to update my ChartSet, which is a accessible by main thread and the new one. In the new thread I use handler.postDelayed(Runnable, 1000) to update data in the next second.
2. After updating data I send a message to handler.
3. In the handleMessage method I dismiss data of chart and again give the data to it and call show().

**Comment by aimicm** [comment]
@navidei  thanks for your share~!

**Comment by aimicm** [comment]
@diogobernardino OK,Thanks!
