### ISSUE TITLE
How to use setGradientFill?

### ISSUE THREAD

**Issue by navidei** [diogobernardino/WilliamChart#77]
I want to show a chart something like the screenshot, so according to documents I need to use setGradientFill method. But I didn't see an example of using this method in the sample app and the arguments int[], position[] aren't self-explained enough. Could you please help? Thanks in advance.
<img width="360" alt="screen shot 1394-06-21 at 5 49 44 pm" src="https://cloud.githubusercontent.com/assets/1954760/9831714/cc8c4910-5976-11e5-994e-c170ce185e78.png">

**Comment by diogobernardino** [comment]
```setGradientFill``` takes 2 ``int[]``, the first defines the set of colors of the gradient (mandatory), the second defines the positions of those colors. Pretty much like what ```LinearGradient ```object takes. If you don't want to define positions you can give it ``null``.

**Comment by navidei** [comment]
Thanks so much. This is a great library.
