### ISSUE TITLE
How to draw Label on specific position.

### ISSUE THREAD

**Issue by skr-sharma** [diogobernardino/WilliamChart#79]
hello @diogobernardino
its nice to put question again here...thanks for your previous reply. moreover i wanted to add label on specific position/point on chart like attached below iOS screenshots has (i want to add  "You" text on the chart)
i am able to draw red line  but getting tough to add "you" text like shown in screenshot.
looking forward to hearing from you.

this is what i want to achieve.
![youline ios](https://cloud.githubusercontent.com/assets/12004449/9961825/45b5a64c-5e40-11e5-88a0-b8de8b988d3f.PNG)

this Android screenshot  is as i have right now.
![without_you android](https://cloud.githubusercontent.com/assets/12004449/9961906/aaddd9fe-5e40-11e5-8e40-d664b8ffe8f4.png)

**Comment by diogobernardino** [comment]
Nice chart. 

The library doesn't support what you need. I might think about implementing a way, not a complete feature since this is something very specific, but something to help someone achieving this. 

Anyway, for the time being if you feel like implementing it to your case, you can perhaps implement a get method under ``ChartView`` returning ``mThresholdValue`` (which is the threshold line Y coordinate in the screen) and having that you might be able to build a ``Tooltip`` in that place. Though not straight forward.

**Comment by skr-sharma** [comment]
very much thanks for reply @diogobernardino
let me try this workaround. :)

**Comment by skr-sharma** [comment]
Hello @diogobernardino
i try your workarround but it did not work...mThresholdValue always return 0.0
any other alternate will appriciate too.
looking forward to hearing from you.

**Comment by diogobernardino** [comment]
There must be something wrong in your code. Have you actually defined a threshold? Otherwise you won't get any value in ``mThresholdValue``.

**Comment by skr-sharma** [comment]
Hello @diogobernardino,
really thanks a lot, it working indeed.

![you_line](https://cloud.githubusercontent.com/assets/12004449/10066211/36760998-62ae-11e5-88c7-c805dffc1d85.png)

**Comment by diogobernardino** [comment]
Cool! I will include that method in the next delivery together with some changes I've done in the setThreshold method.
Btw, I see that the chart you wanted to achieve has the threshold line behind the data. You can change the order which things are drawn and get the same, check ``onDraw`` method of ``ChartView``.

**Comment by skr-sharma** [comment]
sure...let me try.
extremely thanks @diogobernardino

**Comment by kokilayaa** [comment]
@skr-sharma How did you overcome this? Would be  big help :)
