### ISSUE TITLE
How to make BarChartView horizontal to work? 

### ISSUE THREAD

**Issue by PedroCarrillo** [diogobernardino/WilliamChart#80]
I'm using BartChartView setHorizontalScrollBarEnabled(true) but the scroll is not showing and the size of the bars are not following a standard. 

I'm trying to show more than 10 bars and in the cellphone this looks very tiny so I would like to know how to make the scroll function or a way to set the barWidth please

**Comment by diogobernardino** [comment]
Hi. I do not guarantee that the lib supports horizontal scroll, I've never had that in mind while developing it, as well as I have not tested it.
