### ISSUE TITLE
Calculate best step for setAxisBorderValues

### ISSUE THREAD

**Issue by sagits** [diogobernardino/WilliamChart#81]
Hi, i'm trying to implement a method to calculate the best step for setAxisBorderValues:

    public void calculateBestStep(float maxValue, int numOfLabels) {
         int step = 1;
        int numOfLabels = 3;
        if (maxValue >= numOfLabels){
            step = (int) (maxValue / numOfLabels);
        }
       return step;
     }

Do you suggest any other approach?

**Comment by diogobernardino** [comment]
Following [this](https://github.com/diogobernardino/WilliamChart/issues/78) issue I have implemented a way to find a good step from the GCD value using euclidean algorithm. That change has been committed into the DEV branch so far, it should be included in the master soon.

**Comment by ootpapps** [comment]
Here's my solution, you provide a step and the math takes care of ensuring the step is always divisible without a remainder:

public Pair<Integer, Integer> getRoundedMinMaxMeasures(int step) {

        int min = 0;
        int max = 0;

        for (ChartSet chartSet : mListChartSets) {
            for (ChartEntry chartEntry : chartSet.getEntries()) {

                Float value = chartEntry.getValue();

                if (min == 0 || (value < min)) {
                    min = value.intValue();
                }

                if (value > max) {
                    max = value.intValue();
                }
            }
        }

        min = (int) Math.floor((float) min / (float) step) * step;
        max = (int) Math.ceil((float) max / (float) step) * step;

        return new Pair<>(min, max);
    }
