### ISSUE TITLE
Crash on prepare animation 

### ISSUE THREAD

**Issue by kristijandraca** [diogobernardino/WilliamChart#83]
http://crashes.to/s/d9a1068c0d6

**Comment by diogobernardino** [comment]
It seems to me that you're trying to animate an empty chart, not entries in it. Do you confirm?

**Comment by kristijandraca** [comment]
Possible, but I'm not sure because this crash wasn't on my device.

**Comment by diogobernardino** [comment]
Check your code and see if you're allowing that to happen. At least that was my best conclusion from the crash.

**Comment by kristijandraca** [comment]
I can confirm that crash is caused by empty chart. Maybe we should think about prevention within library.
