### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by halfbaked** [diogobernardino/WilliamChart#85]
Perhaps I missed something but I hit on dependency issues in my project after including WilliamChart as a dependency.

the issue centred around support-annotations:23... 

I did the following to get it to compile
```
testCompile 'com.android.support:support-annotations:22.+'
    compile('com.diogobernardino:williamchart:2.1'){
        exclude group: 'com.android.support', module: 'support-annotations'
    }
```

**Comment by diogobernardino** [comment]
Sorry for the late answer, I will assume you already figured it out the problem (or switch to another library). WilliamChart depends indeed on support-annotations library.
