### ISSUE TITLE
Can I invert Y axes?

### ISSUE THREAD

**Issue by Filfmira** [diogobernardino/WilliamChart#88]
I want to set the Y axis to go from the max to min.
For example: setAxisBorderValues(5, 1, 1) insted of setAxisBorderValues(1, 5, 1).
Is there any way to do that?

Thank you so much :)

**Comment by diogobernardino** [comment]
Hmmm, no. Never thought about such thing. And I don't think there's an easy way to make it work.

**Comment by Filfmira** [comment]
Can I then add the Y labels manually?

**Comment by diogobernardino** [comment]
No easy way to do it. They are considered values, not simple labels.
