### ISSUE TITLE
Get info of clicked bar

### ISSUE THREAD

**Issue by MasharipovF** [diogobernardino/WilliamChart#89]
Hello,diogobernardino !!! Thank you for library, it is awesome. I was wondering if i could get info (like its label and value) about the bar i clicked.

like that
![default](https://cloud.githubusercontent.com/assets/15946666/11307534/ac1260e4-8fda-11e5-91d7-35fc0720b961.png)

thank you in advance!

**Comment by diogobernardino** [comment]
I do not offer a standard tooltip out-of-te-box. I believe each application should build its own tooltip therefore I have created a Tooltip object where you can specify a layout (in your case the layout will be a simple TextView with a background which looks like yours). 

Honestly, I'm still not happy with what I've implemented so far, I want to make it easier to build customized tooltipr, and that's what I'm trying to improve right noe. In any case I will still need some time to implement it. So for the time being, either you give it a try looking at the sample examples or you wait until I commit the changes.
