### ISSUE TITLE
Format entry's value displayed in tooltip

### ISSUE THREAD

**Issue by marconealberto** [diogobernardino/WilliamChart#90]
Is that possible at all? Right now when the value is 0 nothing is shown.

**Comment by diogobernardino** [comment]
That's due to the current implementation of Tooltip object...not very flexible.
I've recently done quite a significant number of improvements there, so far you can only find it in DEV branch. Anyway, it will be available in the next release.

**Comment by marconealberto** [comment]
ok thank you! would that include the possibility to choose to show an int instead of a float?

**Comment by diogobernardino** [comment]
Haven't thought about that feature, but sounds indeed something interesting to have.

**Comment by marconealberto** [comment]
yeah, for instance we were thinking of using it in a voting system app, and in that case we would need an int since votes can't be floats..

**Comment by diogobernardino** [comment]
Just implemented what you said. Basically I alow you to set a ``DecimalFormat`` object that will be later used to format the value displayed in the tooltip. For the time being changes are only in the DEV branch, will be available in the next release.
