### ISSUE TITLE
Y Axis Labels : drawing extra undefined lines

### ISSUE THREAD

**Issue by boyfox** [diogobernardino/WilliamChart#91]
Hi Diogo Bernardino!

Firstly thanks your great library. I used this library in my project. I have a following bug with WilliamChart: 

![photo_2015-11-26_19-59-32](https://cloud.githubusercontent.com/assets/3168694/11425738/e4c67f40-9478-11e5-94cd-c1ce87fa7b05.jpg)

here xml part code of related library:

    <com.db.chart.view.BarChartView
        android:id="@+id/barChartView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/block4Sep"
        android:layout_marginTop="35dp"
        android:layout_marginBottom="50dp"
        android:layout_marginLeft="16dp"
        android:layout_marginStart="16dp"
        android:layout_marginRight="16dp"
        android:layout_marginEnd="16dp"/>

This is code:

            String[] mLabels = new String[5];
            float[] mValues = new float[5];
            for (int i = 0; i < lastTestsSize; i++) {
                mLabels[i] = Integer.toString(i + 1);
                mValues[i] = app.mTestResManager.get(i).intValue();
            }
            int rem = 5 - lastTestsSize;
            if (rem > 0) {
                for (int i = 0; i < rem; i++) {
                    mLabels[lastTestsSize + i] = "";
                    mValues[lastTestsSize + i] = 0.0f;
                }
            }
            barChartView.reset();

            int avWidth = Utilities.displaySize.x - Utilities.dp(32);
            int fiveCollWith = 5 * Utilities.dp(38);
            int barSpace = (avWidth - fiveCollWith) / 4;
            barChartView.setBarSpacing(barSpace);

            BarSet dataset = new BarSet(mLabels, mValues);
            dataset.setColor(ContextCompat.getColor(getContext(), R.color.colorPrimary));
            barChartView.addData(dataset);

            barChartView.setXAxis(true);
            barChartView.setXLabels(AxisController.LabelPosition.OUTSIDE);
            barChartView.setYAxis(true);
            barChartView.setYLabels(AxisController.LabelPosition.OUTSIDE);

            barChartView.setLabelsColor(ContextCompat.getColor(getContext(), R.color.colorBlack));
            barChartView.setLabelsFormat(new DecimalFormat("#"));

            Animation anim = new Animation(500);
            anim.setEasing(new CubicEase());
            anim.setAlpha(3);

            barChartView.show(anim);
            barChartView.setVisibility(View.VISIBLE);

I need always draw chart five bar to last five user tests results. And I set every bar width 38dp and I calculated bars spaces to any screen devices in programmatically.
You can see incomprehensible lines under vertical Y labels. 
Do you know how to fix this bug?

**Comment by christianv2m** [comment]
Play with:

.setAxisBorderValues(minValue, maxValue, step)

with "step" you can adjust the number of values to print in the vertical axis, for example:
minValue=0;
maxValue=10;
step=2;

Result: 5 values in the vertical axis.

**Comment by boyfox** [comment]
Good Morning Diogo Bernardino!

I'm very glad to you helped me!

I tried your example, and I understand what you mean. But, every test result have a percent range [0, 100%]. For example : If user solved tests three times and user results like this: 60%, 100%, 30% then I need show 30, 60, 100 in the vertical axis and 1, 2, 3 order numbers of tests in the horizontal axis.
If I set axis border values is setAxisBorderValues(0, 100, 1) I will be get same incorrect drawing Y axis. I think Y axis label not exceeded to height of the chart UI yes? It is need more height?
Please, help me to solve this bug...

**Comment by diogobernardino** [comment]
About showing in the Y axis only the labels which are assigned to your datasets, that's no possible. 
For the "00" you get instead of "100", I find it strange because it doesn't seem to happen to me. Can you show me your layout and chart customization?

**Comment by boyfox** [comment]
Hi Diogo Bernardino!
Firstly I changed bar from BarChartView to StackBarChartView but this is not helped then I fixed this issue with adding this code : barChartView.invalidate(); and chart works fine.

Here is my layout xml, fully: 

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
        android:background="@color/colorBackground"
        android:layout_height="match_parent"
        tools:context="com.stm.studyenglish.fragments.TestPage">
    
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal"
            android:padding="16dp"
            android:gravity="center_vertical"
            android:id="@+id/block1">
            <TextView android:layout_width="wrap_content" android:layout_height="wrap_content"
                android:layout_weight="1"
                android:text="@string/lessons_rage"
                android:textColor="@color/colorPrimaryDark"
                android:textSize="19sp"
                android:gravity="center"
                android:layout_alignParentLeft="true"
                android:layout_alignParentStart="true"
                android:layout_centerVertical="true"
                android:id="@+id/sel_range_lessons_tv" />
    
            <Button
                android:layout_width="wrap_content"
                android:layout_height="45dp"
                android:layout_weight="0"
                android:text="@string/begin_txt"
                android:textColor="@color/colorBackground"
                android:textSize="19sp"
                android:paddingLeft="16dp"
                android:paddingRight="16dp"
                android:id="@+id/beginTestBtn"
                style="?android:attr/borderlessButtonStyle"
                android:background="@drawable/begin_test_btn_selector"
                android:layout_centerVertical="true"
                android:layout_toRightOf="@+id/sel_range_lessons_tv"
                android:layout_toEndOf="@+id/sel_range_lessons_tv" />
    
        </LinearLayout>
    
        <LinearLayout
            android:id="@+id/block2"
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:layout_below="@+id/block1"
            android:background="@drawable/rectangle_border_bold"
            android:gravity="center">
    
            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginRight="30dp"
                android:layout_marginEnd="30dp"
                android:textSize="18sp"
                android:text="@string/with_txt"
                android:gravity="center"
                android:textColor="@color/colorPrimaryDark"
                android:id="@+id/fromLessTV" />
    
            <TextView
                android:layout_width="46dp"
                android:layout_height="27dp"
                android:layout_marginRight="30dp"
                android:layout_marginEnd="30dp"
                android:gravity="center"
                android:textSize="18sp"
                android:text="1"
                android:textColor="@color/colorPrimaryDark"
                android:background="@drawable/rectangle_border"
                android:id="@+id/fromNumberTV" />
    
            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginRight="30dp"
                android:layout_marginEnd="30dp"
                android:textSize="18sp"
                android:gravity="center"
                android:text="@string/by_txt"
                android:textColor="@color/colorPrimaryDark"
                android:id="@+id/toLessTV" />
    
            <TextView
                android:layout_width="46dp"
                android:layout_height="27dp"
                android:gravity="center"
                android:textColor="@color/colorPrimaryDark"
                android:background="@drawable/rectangle_border"
                android:textSize="18sp"
                android:id="@+id/toNumberTV"
                android:text="1" />
    
        </LinearLayout>
    
        <RelativeLayout
            android:id="@+id/block3"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="20dp"
            android:layout_below="@+id/block2"
            android:paddingLeft="@dimen/activity_vertical_margin"
            android:paddingStart="@dimen/activity_vertical_margin"
            android:paddingRight="@dimen/activity_vertical_margin">
            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_alignParentLeft="true"
                android:layout_toLeftOf="@+id/lastTestValTV"
                android:textSize="18sp"
                android:text="@string/last_test_res"
                android:textColor="@color/colorPrimaryDark"
                android:id="@+id/lastTestTitleTV" />
            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_alignParentRight="true"
                android:textSize="18sp"
                android:text="-"
                android:textColor="@color/colorPrimaryDark"
                android:id="@+id/lastTestValTV" />
        </RelativeLayout>
    
        <View
            android:id="@+id/block3Sep"
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:layout_below="@+id/block3"
            android:layout_marginTop="2dp"
            android:background="@color/colorGray"
            android:layout_marginLeft="@dimen/activity_vertical_margin"
            android:layout_marginStart="@dimen/activity_vertical_margin"
            android:layout_marginRight="@dimen/activity_vertical_margin"
            android:layout_marginEnd="@dimen/activity_vertical_margin"/>
    
        <RelativeLayout
            android:id="@+id/block4"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="10dp"
            android:layout_below="@+id/block3Sep"
            android:paddingLeft="@dimen/activity_vertical_margin"
            android:paddingStart="@dimen/activity_vertical_margin"
            android:paddingRight="@dimen/activity_vertical_margin">
            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_alignParentLeft="true"
                android:layout_toLeftOf="@+id/last5TestValTV"
                android:textSize="18sp"
                android:text="@string/last_five_test_res"
                android:textColor="@color/colorPrimaryDark"
                android:id="@+id/last5TestTitleTV" />
            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_alignParentRight="true"
                android:textSize="18sp"
                android:text="-"
                android:textColor="@color/colorPrimaryDark"
                android:id="@+id/last5TestValTV" />
        </RelativeLayout>
    
        <View
            android:id="@+id/block4Sep"
            android:layout_width="match_parent"
            android:layout_height="1dp"
            android:layout_below="@+id/block4"
            android:layout_marginTop="2dp"
            android:background="@color/colorGray"
            android:layout_marginLeft="@dimen/activity_vertical_margin"
            android:layout_marginStart="@dimen/activity_vertical_margin"
            android:layout_marginRight="@dimen/activity_vertical_margin"
            android:layout_marginEnd="@dimen/activity_vertical_margin" />
    
        <com.db.chart.view.StackBarChartView
            android:id="@+id/barChartView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@+id/block4Sep"
            android:layout_marginTop="35dp"
            android:layout_marginBottom="35dp"
            android:layout_marginLeft="@dimen/activity_vertical_margin"
            android:layout_marginStart="@dimen/activity_vertical_margin"
            android:layout_marginRight="@dimen/activity_vertical_margin"
            android:layout_marginEnd="@dimen/activity_vertical_margin" />
    
    </RelativeLayout>

activity_vertical_margin equals to 16dp.

this is code : 
            
            barChartView.invalidate();
            barChartView.reset();
            BarSet dataset = new BarSet(mLabels, mValues);
            dataset.setColor(ContextCompat.getColor(getContext(), R.color.colorPrimary));

            int avWidth = Utilities.displaySize.x - Utilities.dp(32);
            int fiveCollWith = 5 * Utilities.dp(56);
            int barSpace = (avWidth - fiveCollWith) / 4;

            barChartView.setBarSpacing(barSpace);
            barChartView.addData(dataset);

            barChartView.setXAxis(true);
            barChartView.setXLabels(AxisController.LabelPosition.OUTSIDE);
            barChartView.setYAxis(true);
            barChartView.setYLabels(AxisController.LabelPosition.OUTSIDE);
            barChartView.setAxisBorderValues(0, axisMaxVal, 10);

            barChartView.setLabelsColor(ContextCompat.getColor(getContext(), R.color.colorBlack));
            barChartView.setLabelsFormat(new DecimalFormat("#"));

            Animation anim = new Animation(500);
            anim.setEasing(new CubicEase());
            anim.setAlpha(3);

            barChartView.show(anim);
            barChartView.setVisibility(View.VISIBLE);

Thanks for great library!

**Comment by boyfox** [comment]
I have a news, appears following new bug only Android 6.0:

    java.lang.IllegalArgumentException: Step value must be a divisor of distance between minValue and maxValue
            at com.db.chart.view.AxisController.setBorderValues(AxisController.java:330)
            at com.db.chart.view.ChartView.setAxisBorderValues(ChartView.java:1204)
            at com.db.chart.view.BaseStackBarChartView.setAxisBorderValues(BaseStackBarChartView.java:196)
            at com.stm.studyenglish.fragments.TestPage.checkLastTest(TestPage.java:258)
            at com.stm.studyenglish.fragments.TestPage.onViewCreated(TestPage.java:113)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by diogobernardino** [comment]
If minValue == maxValue then that exception makes totally sense. The bug is in your code.
