### ISSUE TITLE
Issue with big numbers in barchart

### ISSUE THREAD

**Issue by christianv2m** [diogobernardino/WilliamChart#92]
Hi, 
In my case the chart works fine with small values, but when I try to make a graph with values like 9.999.999 then it gets stuck. (kills the device)
I am using Barchart, following the example, with 2 series of a chart that:
- In horizontal I print the months (12 values).
- In vertical, I show income and expenses per month.
- Min value: 0
-Max value: 9.999.999

Following code I saw that in that graph, considered vertical, in the method calcLabels() in AxisController, it enters in a loop of a while, executed 9.999.999 times, so it kills the device.

Because orientation is vertical, I only can define variable "step" of verController, but in method "onPreDraw" of file ChartView.java, it calls always verController.init() and horController.init().
In horController.init() -> defineLabels()->calcLabels() [File AxisController.java Line 283] there is a while that is executed 9.999.999 times killing the device. Could be executed less times if I could edit the value of "step", but I can only edit "step" value of verController, not horController.

========
How I call:
========

maxValue=10999996;
step=2749999;

barChart.setBorderSpacing(5)
                .setAxisBorderValues(0, maxValue, step)
                .setGrid(BarChartView.GridType.FULL, 4, 4, gridPaint)
                .setYAxis(true)
                .setXLabels(XController.LabelPosition.OUTSIDE)
                .setYLabels(YController.LabelPosition.OUTSIDE)
                .setLabelsColor(Color.parseColor(labels_color))
                .setAxisColor(Color.parseColor(axis_color));

**Comment by christianv2m** [comment]
Hi @diogobernardino ,

    Our App based all the reporting in your library of graphs, and we can't publish it because of this issue. It would help us to know if you plan to solve it in short period, so we wait, or long so we have to find a work arround.

Thanks!

**Comment by diogobernardino** [comment]
Just by looking at the code you using and my implementation I don't understand how can the ``while`` condition run that amount of times since you have a step of 2749999. If you really confirm that that's the case then I will need more time to run your code and understand where is my implementation failing. Shouldn't be difficult to spot the problem but I can't make a commitment about when will I have time to do it. If you're really in a hurry I would recommend you to try to fix it.

**Comment by christianv2m** [comment]
Hi,
   Sorry for my explanation, will try to explain better and with more detail.

   The kind of graph i want to print is the next:

![screenshot_2015-11-30-10-23-57](https://cloud.githubusercontent.com/assets/1267758/11468182/c776f14a-974d-11e5-8ddb-e3d089b10f1b.png)

Horizontal axis for months, vertical axis for salary income (green) or expenses (red).
How do we use the API:

  - We have two float array with income[] and expenses[].
  - We want always to have 4 steps to paint the grid with 4 lines as u see in the image, so we compute the maxValue, and the variable step.
   - Finally we pass the values to your API, in something like that:

{...}
barChart.setBorderSpacing(5)
                .setAxisBorderValues(0, maxValue, step)
                .setGrid(BarChartView.GridType.FULL, 4, 4, gridPaint)
                .setYAxis(true)
                .setXLabels(XController.LabelPosition.OUTSIDE)
                .setYLabels(YController.LabelPosition.OUTSIDE)
                .setLabelsColor(Color.parseColor(labels_color))
                .setAxisColor(Color.parseColor(axis_color));
{...}
barChart.show(new Animation().setEndAction(chartOneAction))

where
     - maxValue = Bigger value from income[] or exepnses[]
     - step = Something like maxValue/4.
     
   As you see in the image, with normal values the graph works ok.
   The problem comes when instead of working with values arround 45.000, we work with values arround 1.000.000.
   In that case, high performance devices works, but in average performance devices the App crashes.
   Debugging we saw the next:

In your class ChartView, there are:
- final XController horController;
- final YController verController;

In the same class, there is a Listener called "OnPreDrawListener drawListener" implemented.
Inside this implementation "onPreDraw" there is the next calls:

 {...}
 - verController.init();

 {...}

 - horController.init();

 {...}

Inside verController.init(), we can follow the next calls:
      verController.init() -> defineLabels() -> calcLabels().
      At the end of calcLabels() method, there is a loop:

      while(pos <= maxLabelValue){
            result.add(pos);
            pos += step;
        }
      in this execution, step = step defined in my code, so the loop should be executed something similar to 4-5 times.
      THIS EXECUTION IS OK!

Inside horController.init() we can follor the next calls:
	horController.init() -> defineLabels() -> calcLabels().
       In the same loop as before, the variable step has a value of 1.
       When we work with values of the order of 1.000.000, the variable maxLabelValue = 1.000.000, and with step of 1, the loop is executed 1.000.000 times, and kills the device.

Studing how can I define the step of horController, I saw that I can't, because I only can define 1 step, and is in the verController.
 
I tried to solve the problem creating my own class MyBarChart that extends your classes, but because the variables are private, I can't modify them.



I think this is a bit more detailed :D.
Thanks for your time, I really appreciate it.

**Comment by christianv2m** [comment]
Hi again,

    I did a fork and add a method to the class ChartView to solve my problem.
    The method is the next:

/**
 * Sets an specific step to the orientation specified.
 * @param orientation
 * @param step
 * @return
 */
public ChartView setSpecificStep(Orientation orientation,int step){
	if(orientation == Orientation.VERTICAL)
		verController.step=step;
	else
		horController.step=step;
	return this;
}

Probably there is a better way or more elegant to do it, I let to you to improve it :dancer: 
Finally, the call is the next:

barChart.setBorderSpacing(5)
                .setAxisBorderValues(0, maxValue, step)
                .setGrid(BarChartView.GridType.FULL, 4, 4, gridPaint)
                **.setSpecificStep(ChartView.Orientation.HORIZONTAL,step)**
                .setYAxis(true)
                .setXLabels(XController.LabelPosition.OUTSIDE)
                .setYLabels(YController.LabelPosition.OUTSIDE)
                .setLabelsColor(Color.parseColor(labels_color))
                .setAxisColor(Color.parseColor(axis_color));

I would prefer to use your library more than my fork, so if you could add this, I would appreciate.
Thanks for all and congrats for the lib!!

**Comment by diogobernardino** [comment]
Happy to know you found a solution. As soon as I have the time I will take a look at the issue and the way you managed to solve it as well, thanks. So for the time being I will keep the issue opened.

**Comment by diogobernardino** [comment]
It turns out that this wasn't really a code performance issue but a code mistake. Only the axis handling values (Y axis in case of a vertical chart) should do a calculation of labels, the other axis takes them directly from the dataset.
I have committed the fix into the DEV branch. It's really simple. You can check the last commit done and apply the change on your side if you want. It will be included in the next release.

**Comment by christianv2m** [comment]
What you said about axis has all the sense.
I will wait for your next release to attach it and discard my change.
Thanks for the speed, appreciate it!
