### ISSUE TITLE
[Enhancement] Strings in tooltips or labels on Barchart

### ISSUE THREAD

**Issue by christianv2m** [diogobernardino/WilliamChart#93]
The library only lets to work in numeric values [Only checked with Barchart].
Would it be nice:
- Being able to define some text in the global horizontal and vertical axis. (Something like explaining the meaning of each axis).
- Being able to define string in the value showed in each vertical line of the grid.
- Being able to put a title in the graph.

**Comment by diogobernardino** [comment]
I couldn't understand the title of the issue, and then the content of the issue doesn't seem to match the title. Anyway, I tried to answer the points you mentioned.

*Being able to define some text in the global horizontal and vertical axis. (Something like explaining the meaning of each axis).*
You can do you that easily in your layout, needless feature to add to the library.

*Being able to define string in the value showed in each vertical line of the grid.*
Couldn't understand, perhaps you can show an example.

*Being able to put a title in the graph.*
You can do you that easily in your layout, needless feature to add to the library.

In any case thanks for suggesting.
