### ISSUE TITLE
Y axis labels displayed under chart content

### ISSUE THREAD

**Issue by ladia12** [diogobernardino/WilliamChart#95]
I made the following change in the sample. Changed the Y axis labels from NONE to INDISE.
setYLabels(AxisController.LabelPosition.INSIDE)
As a result I couldnt see many of the Y axis labels.
Below is screenshot, and you can check out the bug in the first graph.
![screenshot_2015-12-06-19-45-35]
(https://cloud.githubusercontent.com/assets/3083995/11613755/8127f798-9c52-11e5-8180-b96272d5e13b.png)

**Comment by diogobernardino** [comment]
That's correct. If you set them as INSIDE (of chart area), they will be displayed inside of the chart area.

**Comment by ladia12** [comment]
I know it should be displayed inside. But see the labels 1,2,3 are missing. It should be at least above the drawn graphs so that labels are at least visible

**Comment by diogobernardino** [comment]
I see what you mean. That's happening because I'm drawing first the lables and the chart content afterwards. Right now I don't completely recall but I seem to remember that there was a reason for that. I will re-open the issue and think about it later.

**Comment by ashmosaheb** [comment]
Has this been resolved? I really need the y axis labels to display on top of the chart when inside. This especially important when using a horizontal bar chart.

Is there anyway of achieving this with current library now. Like getting the view for each bar entry?

Ideally I want to do something like this..

[Horizontal bar label 1           4%]
[Horizontal bar label 2   ]      2%

**Comment by diogobernardino** [comment]
If you want to have that now just change the order of the draw* methods inside the onDraw of ChartView class.
Next release should have this solved already.

**Comment by Polyterative** [comment]
Sorry to write on this again, but how can I achieve the functionality @ladia12 desider? I should create my own class extending ChartView and overriding that method? 
[I have to draw charts before labels too](http://imgur.com/a/Ar6O8)
